CREATE TABLE [dbo].[AirportInformationVersions] (
    [AirportInformationId] INT            IDENTITY (1, 1) NOT NULL,
    [LocationDescription]  NVARCHAR (MAX) NULL,
    [TimeZoneDescription]  NVARCHAR (MAX) NULL,
    [Contacts]             NVARCHAR (MAX) NULL,
    [TransferCity]         NVARCHAR (MAX) NULL,
    [CarRental]            NVARCHAR (MAX) NULL,
    [CarParking]           NVARCHAR (MAX) NULL,
    [AirportFacilities]    NVARCHAR (MAX) NULL,
    [VisaInformation]      NVARCHAR (MAX) NULL,
    [CheckInInformation]   NVARCHAR (MAX) NULL,
    [ParentId]             INT            NOT NULL,
    [UrlIdentifier]        NVARCHAR (MAX) NULL,
    [CmsName]              NVARCHAR (MAX) NULL,
    [Version]              INT            NOT NULL,
    [IsDraft]              BIT            NOT NULL,
    [CreatedById]          INT            NULL,
    [CreatedDate]          DATETIME2 (7)  NULL,
    [ApprovedById]         INT            NULL,
    [ApprovedDate]         DATETIME2 (7)  NULL,
    [PublishedById]        INT            NULL,
    [PublishedDate]        DATETIME2 (7)  NULL,
    [UnpublishedById]      INT            NULL,
    [UnpublishedDate]      DATETIME2 (7)  NULL,
    [PageTitle]            NVARCHAR (MAX) NULL,
    [Keywords]             NVARCHAR (MAX) NULL,
    [Description]          NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([AirportInformationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

