CREATE TABLE [dbo].[AirportInformationLabels] (
    [AirportInformationLabelsId]  INT            IDENTITY (1, 1) NOT NULL,
    [SearchModuleTitle]           NVARCHAR (MAX) NULL,
    [SearchModuleCountryLabel]    NVARCHAR (MAX) NULL,
    [SearchModuleCityLabel]       NVARCHAR (MAX) NULL,
    [SearchModuleSearchButton]    NVARCHAR (MAX) NULL,
    [SearchModuleSelectCountry]   NVARCHAR (MAX) NULL,
    [SearchModuleSelectCity]      NVARCHAR (MAX) NULL,
    [AirportLocationTitle]        NVARCHAR (MAX) NULL,
    [AirportLocationSeeMapLink]   NVARCHAR (MAX) NULL,
    [AirportTimeZoneTitle]        NVARCHAR (MAX) NULL,
    [AirportContactsTitle]        NVARCHAR (MAX) NULL,
    [AirportTransferCityTitle]    NVARCHAR (MAX) NULL,
    [AirportCarRentalTitle]       NVARCHAR (MAX) NULL,
    [AirportCarParkingTitle]      NVARCHAR (MAX) NULL,
    [AirportFacilitiesTitle]      NVARCHAR (MAX) NULL,
    [AirportVisaInformationTitle] NVARCHAR (MAX) NULL,
    [AirportCheckInTitle]         NVARCHAR (MAX) NULL,
    [AirportListTitle]            NVARCHAR (MAX) NULL,
    [AirportListSelect]           NVARCHAR (MAX) NULL,
    [AirportListGo]               NVARCHAR (MAX) NULL,
    [LanguageId]                  INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([AirportInformationLabelsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

