CREATE TABLE [dbo].[BookingHistoryLabels] (
    [Language]                            NVARCHAR (128) NOT NULL,
    [ActiveBookingsModuleTitle]           NVARCHAR (MAX) NULL,
    [ActiveBookingsPleaseNote]            NVARCHAR (MAX) NULL,
    [ActiveBookingsDueToExpire]           NVARCHAR (MAX) NULL,
    [Reference]                           NVARCHAR (MAX) NULL,
    [PrimaryPassengerLastName]            NVARCHAR (MAX) NULL,
    [NumberOfPassengers]                  NVARCHAR (MAX) NULL,
    [Route]                               NVARCHAR (MAX) NULL,
    [BookingDate]                         NVARCHAR (MAX) NULL,
    [DepartureDate]                       NVARCHAR (MAX) NULL,
    [Type]                                NVARCHAR (MAX) NULL,
    [ViewFullHistory]                     NVARCHAR (MAX) NULL,
    [BookingHistoryModuleTitle]           NVARCHAR (MAX) NULL,
    [BookingHistoryOnlyShowMe]            NVARCHAR (MAX) NULL,
    [BookingHistoryUpdateFilter]          NVARCHAR (MAX) NULL,
    [BookingHistorySortBy]                NVARCHAR (MAX) NULL,
    [BookingHistoryResultsDisplayed]      NVARCHAR (MAX) NULL,
    [ViewBookingModuleTitle]              NVARCHAR (MAX) NULL,
    [ViewBookingPrimaryPassengerLastName] NVARCHAR (MAX) NULL,
    [ViewBookingReference]                NVARCHAR (MAX) NULL,
    [ViewBookingSubmit]                   NVARCHAR (MAX) NULL,
    [NoBookings]                          NVARCHAR (MAX) NULL,
    [PaginationNext]                      NVARCHAR (MAX) NULL,
    [PaginationPrevious]                  NVARCHAR (MAX) NULL,
    [FilterAll]                           NVARCHAR (MAX) NULL,
    [FilterConfirmed]                     NVARCHAR (MAX) NULL,
    [FilterPaymentOutstanding]            NVARCHAR (MAX) NULL,
    [FilterExpiredCancelled]              NVARCHAR (MAX) NULL,
    [FilterCompleted]                     NVARCHAR (MAX) NULL,
    [SortBookingRef]                      NVARCHAR (MAX) NULL,
    [SortBookingDate]                     NVARCHAR (MAX) NULL,
    [SortDepartureDate]                   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

