CREATE TABLE [dbo].[BookingLabels] (
    [Language]                                                                   NVARCHAR (128) NOT NULL,
    [AddPassengers]                                                              NVARCHAR (MAX) NULL,
    [AmendBaggage]                                                               NVARCHAR (MAX) NULL,
    [ChangeSseats]                                                               NVARCHAR (MAX) NULL,
    [ChangeDates]                                                                NVARCHAR (MAX) NULL,
    [CancelSector]                                                               NVARCHAR (MAX) NULL,
    [AmendBooking]                                                               NVARCHAR (MAX) NULL,
    [SelectSectors]                                                              NVARCHAR (MAX) NULL,
    [SeatsAndBaggage]                                                            NVARCHAR (MAX) NULL,
    [ConfirmChanges]                                                             NVARCHAR (MAX) NULL,
    [BookingRef]                                                                 NVARCHAR (MAX) NULL,
    [ThankYou]                                                                   NVARCHAR (MAX) NULL,
    [YourDetailsHaveBeenUpdated]                                                 NVARCHAR (MAX) NULL,
    [FlightHeld]                                                                 NVARCHAR (MAX) NULL,
    [YourFlightIsBeingHeldFor]                                                   NVARCHAR (MAX) NULL,
    [Hours]                                                                      NVARCHAR (MAX) NULL,
    [Mins]                                                                       NVARCHAR (MAX) NULL,
    [Untill]                                                                     NVARCHAR (MAX) NULL,
    [Options]                                                                    NVARCHAR (MAX) NULL,
    [ToChangeYourBookingSelectAmendBooking]                                      NVARCHAR (MAX) NULL,
    [CancelBooking]                                                              NVARCHAR (MAX) NULL,
    [RepeatBooking]                                                              NVARCHAR (MAX) NULL,
    [PrintEReciept]                                                              NVARCHAR (MAX) NULL,
    [WeNeedALittleMoreInformationAboutEachPassenger]                             NVARCHAR (MAX) NULL,
    [CompleteAdvancedPassengerInformation]                                       NVARCHAR (MAX) NULL,
    [BeforeYouFly]                                                               NVARCHAR (MAX) NULL,
    [YourBookingReference]                                                       NVARCHAR (MAX) NULL,
    [PleaseArriveAtLeast]                                                        NVARCHAR (MAX) NULL,
    [HoursBeforeYourFlight]                                                      NVARCHAR (MAX) NULL,
    [ToAllowForCheckin]                                                          NVARCHAR (MAX) NULL,
    [AnEmailHasBeenSentTo]                                                       NVARCHAR (MAX) NULL,
    [YourBookingIsBeingHeldUntil]                                                NVARCHAR (MAX) NULL,
    [ToCompleteTheBookingYouMustPayAtPaymentPoint]                               NVARCHAR (MAX) NULL,
    [SeePaymentPoints]                                                           NVARCHAR (MAX) NULL,
    [YourPaymentReference]                                                       NVARCHAR (MAX) NULL,
    [TotalPayment]                                                               NVARCHAR (MAX) NULL,
    [YourPaymentDetails]                                                         NVARCHAR (MAX) NULL,
    [CreditCard]                                                                 NVARCHAR (MAX) NULL,
    [Print]                                                                      NVARCHAR (MAX) NULL,
    [EmailBooking]                                                               NVARCHAR (MAX) NULL,
    [ChangeMyBooking]                                                            NVARCHAR (MAX) NULL,
    [EmailAddress]                                                               NVARCHAR (MAX) NULL,
    [Send]                                                                       NVARCHAR (MAX) NULL,
    [Cancel]                                                                     NVARCHAR (MAX) NULL,
    [On]                                                                         NVARCHAR (MAX) NULL,
    [YourPaymentSummary]                                                         NVARCHAR (MAX) NULL,
    [JourneyTotal]                                                               NVARCHAR (MAX) NULL,
    [BillingAddress]                                                             NVARCHAR (MAX) NULL,
    [TotalPaymentDue]                                                            NVARCHAR (MAX) NULL,
    [Depart]                                                                     NVARCHAR (MAX) NULL,
    [FlightNo]                                                                   NVARCHAR (MAX) NULL,
    [Departing]                                                                  NVARCHAR (MAX) NULL,
    [Arrival]                                                                    NVARCHAR (MAX) NULL,
    [Duration]                                                                   NVARCHAR (MAX) NULL,
    [Hour]                                                                       NVARCHAR (MAX) NULL,
    [Minutes]                                                                    NVARCHAR (MAX) NULL,
    [Plus]                                                                       NVARCHAR (MAX) NULL,
    [Outbound]                                                                   NVARCHAR (MAX) NULL,
    [Return]                                                                     NVARCHAR (MAX) NULL,
    [Passengers]                                                                 NVARCHAR (MAX) NULL,
    [FareType]                                                                   NVARCHAR (MAX) NULL,
    [Baggage]                                                                    NVARCHAR (MAX) NULL,
    [Seat]                                                                       NVARCHAR (MAX) NULL,
    [Extra]                                                                      NVARCHAR (MAX) NULL,
    [Taxes]                                                                      NVARCHAR (MAX) NULL,
    [SubTotal]                                                                   NVARCHAR (MAX) NULL,
    [AdultTraveler]                                                              NVARCHAR (MAX) NULL,
    [ChildTraveler]                                                              NVARCHAR (MAX) NULL,
    [InfantTraveler]                                                             NVARCHAR (MAX) NULL,
    [NoChange]                                                                   NVARCHAR (MAX) NULL,
    [PayToChange]                                                                NVARCHAR (MAX) NULL,
    [FreeToChange]                                                               NVARCHAR (MAX) NULL,
    [HandBaggage7Kg]                                                             NVARCHAR (MAX) NULL,
    [Only]                                                                       NVARCHAR (MAX) NULL,
    [CheckedBaggage20Kg]                                                         NVARCHAR (MAX) NULL,
    [CheckedBaggage30Kg]                                                         NVARCHAR (MAX) NULL,
    [CheckedBaggage40Kg]                                                         NVARCHAR (MAX) NULL,
    [Insurance]                                                                  NVARCHAR (MAX) NULL,
    [Ref]                                                                        NVARCHAR (MAX) NULL,
    [BasedOn24HourClockAllTimesShownAreLocal]                                    NVARCHAR (MAX) NULL,
    [Total]                                                                      NVARCHAR (MAX) NULL,
    [InclusiveOfAllTaxes]                                                        NVARCHAR (MAX) NULL,
    [FeesAndDiscounts]                                                           NVARCHAR (MAX) NULL,
    [PromoDiscount]                                                              NVARCHAR (MAX) NULL,
    [FeesApplicable]                                                             NVARCHAR (MAX) NULL,
    [CreditDebitCard]                                                            NVARCHAR (MAX) NULL,
    [ManageBooking]                                                              NVARCHAR (MAX) NULL,
    [FlightSearch]                                                               NVARCHAR (MAX) NULL,
    [CheckedBaggage10Kg]                                                         NVARCHAR (MAX) NULL,
    [WaitingTime]                                                                NVARCHAR (MAX) NULL,
    [BookingNotFound]                                                            NVARCHAR (MAX) NULL,
    [BookingAllFlown]                                                            NVARCHAR (MAX) NULL,
    [BookingExpired]                                                             NVARCHAR (MAX) NULL,
    [BookingMustBeAccessedViaTA]                                                 NVARCHAR (MAX) NULL,
    [SorryYourFlightIsDepartingInLessThan]                                       NVARCHAR (MAX) NULL,
    [HoursAndCannotBeUpdated]                                                    NVARCHAR (MAX) NULL,
    [ChangeSeatsAndBaggage]                                                      NVARCHAR (MAX) NULL,
    [PleaseCallTheCallCentre]                                                    NVARCHAR (MAX) NULL,
    [PleaseContactTheCallCentreToRemovePrimaryPassengersOrTravellingWithInfants] NVARCHAR (MAX) NULL,
    [Journey]                                                                    NVARCHAR (MAX) NULL,
    [PleaseBringYourPassportsAndCheckinAtTheAirport]                             NVARCHAR (MAX) NULL,
    [PleaseCheckYourContactDetails]                                              NVARCHAR (MAX) NULL,
    [IfYouRequireChangesToYourContactDetailsPleaseCallFlydubaiOnXXXX]            NVARCHAR (MAX) NULL,
    [PrimaryPassengerContactDetails]                                             NVARCHAR (MAX) NULL,
    [NoPrimaryPassenger]                                                         NVARCHAR (MAX) NULL,
    [InterlineBooking]                                                           NVARCHAR (MAX) NULL,
    [PNRisLocked]                                                                NVARCHAR (MAX) NULL,
    [BusBooking]                                                                 NVARCHAR (MAX) NULL,
    [CannotChangeFlightToThisDate]                                               NVARCHAR (MAX) NULL,
    [LogicalFlightSubTotal]                                                      NVARCHAR (MAX) NULL,
    [TheFollowingVouchersHaveBeenSentTo]                                         NVARCHAR (MAX) NULL,
    [VouchersDescription]                                                        NVARCHAR (MAX) NULL,
    [Remove]                                                                     NVARCHAR (MAX) NULL,
    [Penalty]                                                                    NVARCHAR (MAX) NULL,
    [NonRefundableInsurance]                                                     NVARCHAR (MAX) NULL,
    [OptionalExtras]                                                             NVARCHAR (MAX) NULL,
    [InFlightEntertainment]                                                      NVARCHAR (MAX) NULL,
    [InFlightEntertainmentPackageDescription]                                    NVARCHAR (MAX) NULL,
    [NoInFlightEntertainment]                                                    NVARCHAR (MAX) NULL,
    [InFlightEntertainmentUnavailable]                                           NVARCHAR (MAX) NULL,
    [HotMeal]                                                                    NVARCHAR (MAX) NULL,
    [NoMealOptionsInfent]                                                        NVARCHAR (MAX) NULL,
    [Economy]                                                                    NVARCHAR (MAX) NULL,
    [Business]                                                                   NVARCHAR (MAX) NULL,
    [Basic]                                                                      NVARCHAR (MAX) NULL,
    [BusinessHandBaggage]                                                        NVARCHAR (MAX) NULL,
    [Premium]                                                                    NVARCHAR (MAX) NULL,
    [BuySnacksAndDrinksOnBoard]                                                  NVARCHAR (MAX) NULL,
    [Meal]                                                                       NVARCHAR (MAX) NULL,
    [Meals]                                                                      NVARCHAR (MAX) NULL,
    [Unassigned]                                                                 NVARCHAR (MAX) NULL,
    [UpgradeToBusiness]                                                          NVARCHAR (MAX) NULL,
    [NOIFEInfant]                                                                NVARCHAR (MAX) NULL,
    [NOSeatInfant]                                                               NVARCHAR (MAX) NULL,
    [NOBaggageInfant]                                                            NVARCHAR (MAX) NULL,
    [MakeChangesToTheCompleteAdvancedPassengerInformation]                       NVARCHAR (MAX) NULL,
    [PleaseUpdateTheAdvancedPassengerInformation]                                NVARCHAR (MAX) NULL,
    [ToolTipAmmendAddPassenger]                                                  NVARCHAR (MAX) NULL,
    [RestrictedFareBasisErrorText]                                               NVARCHAR (MAX) NULL,
    [TimerTitle]                                                                 NVARCHAR (MAX) NULL,
    [TimerMessage]                                                               NVARCHAR (MAX) NULL,
    [TimerContinueButton]                                                        NVARCHAR (MAX) NULL,
    [PrintButton]                                                                NVARCHAR (100) NULL,
    [AddServices]                                                                NVARCHAR (100) NULL,
    [CabinClass]                                                                 NVARCHAR (100) NULL,
    [GDSCannotProceedMessage]                                                    NVARCHAR (MAX) NULL,
    [GDSConditionsNotMetErrorMessage]                                            NVARCHAR (MAX) NULL,
    [Back]                                                                       NVARCHAR (100) NULL,
    [GDSCannotProceedHeaderMessage]                                              NVARCHAR (MAX) NULL,
    [CheckIn]                                                                    NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);





















