CREATE TABLE [dbo].[ContactUsLabels] (
    [ContactUsLabelsId]                     INT            IDENTITY (1, 1) NOT NULL,
    [ModuleTitle]                           NVARCHAR (MAX) NULL,
    [MandatoryFields]                       NVARCHAR (MAX) NULL,
    [Title]                                 NVARCHAR (MAX) NULL,
    [TitleSelect]                           NVARCHAR (MAX) NULL,
    [Titles]                                NVARCHAR (MAX) NULL,
    [FirstName]                             NVARCHAR (MAX) NULL,
    [MiddleName]                            NVARCHAR (MAX) NULL,
    [LastName]                              NVARCHAR (MAX) NULL,
    [Email]                                 NVARCHAR (MAX) NULL,
    [Country]                               NVARCHAR (MAX) NULL,
    [HomeNumber]                            NVARCHAR (MAX) NULL,
    [MobileNumber]                          NVARCHAR (MAX) NULL,
    [BookingReference]                      NVARCHAR (MAX) NULL,
    [Subject]                               NVARCHAR (MAX) NULL,
    [Message]                               NVARCHAR (MAX) NULL,
    [SendCopy]                              NVARCHAR (MAX) NULL,
    [Submit]                                NVARCHAR (MAX) NULL,
    [SmallModuleHeadingText]                NVARCHAR (MAX) NULL,
    [SmallModuleFaqsLinkLabel]              NVARCHAR (MAX) NULL,
    [SmallModuleFaqsSummaryFormatString]    NVARCHAR (MAX) NULL,
    [SmallModuleSummaryText]                NVARCHAR (MAX) NULL,
    [SmallModuleButtonText]                 NVARCHAR (MAX) NULL,
    [SendMessageSuccess]                    NVARCHAR (MAX) NULL,
    [SendMessageError]                      NVARCHAR (MAX) NULL,
    [SendMessageSuccessHeading]             NVARCHAR (MAX) NULL,
    [SendMessageErrorHeading]               NVARCHAR (MAX) NULL,
    [CountryDropDownSelectText]             NVARCHAR (MAX) NULL,
    [HomeNumberCountryDropDownSelectText]   NVARCHAR (MAX) NULL,
    [MobileNumberCountryDropDownSelectText] NVARCHAR (MAX) NULL,
    [SubjectLabel]                          NVARCHAR (MAX) NULL,
    [LanguageId]                            INT            NOT NULL,
    [City]                                  NVARCHAR (MAX) NULL,
    [Address]                               NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ContactUsLabelsId] ASC)
);



