CREATE TABLE [dbo].[DestinationGuideLabels] (
    [DestinationGuideLabelsId] INT            IDENTITY (1, 1) NOT NULL,
    [MapTitle]                 NVARCHAR (MAX) NULL,
    [FormLabel]                NVARCHAR (MAX) NULL,
    [SelectYourStartingPoint]  NVARCHAR (MAX) NULL,
    [SelectCountry]            NVARCHAR (MAX) NULL,
    [SelectCity]               NVARCHAR (MAX) NULL,
    [MaxFlightTime]            NVARCHAR (MAX) NULL,
    [Hours]                    NVARCHAR (MAX) NULL,
    [CurrentlyDisplaying]      NVARCHAR (MAX) NULL,
    [ViewDestinationGuide]     NVARCHAR (MAX) NULL,
    [BookNow]                  NVARCHAR (MAX) NULL,
    [Airport]                  NVARCHAR (MAX) NULL,
    [Country]                  NVARCHAR (MAX) NULL,
    [City]                     NVARCHAR (MAX) NULL,
    [FlightTime]               NVARCHAR (MAX) NULL,
    [ThingsToDo]               NVARCHAR (MAX) NULL,
    [Beach]                    NVARCHAR (MAX) NULL,
    [Nightlife]                NVARCHAR (MAX) NULL,
    [Family]                   NVARCHAR (MAX) NULL,
    [Romantic]                 NVARCHAR (MAX) NULL,
    [Culture]                  NVARCHAR (MAX) NULL,
    [Sports]                   NVARCHAR (MAX) NULL,
    [Go]                       NVARCHAR (MAX) NULL,
    [ViewMap]                  NVARCHAR (MAX) NULL,
    [CloseMap]                 NVARCHAR (MAX) NULL,
    [TooltipHeading]           NVARCHAR (MAX) NULL,
    [TooltipText]              NVARCHAR (MAX) NULL,
    [LanguageId]               INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([DestinationGuideLabelsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

