CREATE TABLE [dbo].[FlightStatusLabels] (
    [FlightStatusLabelsId]                       INT            IDENTITY (1, 1) NOT NULL,
    [ModuleTitle]                                NVARCHAR (MAX) NULL,
    [SidebarModuleTitle]                         NVARCHAR (MAX) NULL,
    [SelectDateInformationText]                  NVARCHAR (MAX) NULL,
    [SelectDateArrivalLabel]                     NVARCHAR (MAX) NULL,
    [ShortSelectDateArrivalLabel]                NVARCHAR (MAX) NULL,
    [SearchMethodQuestion]                       NVARCHAR (MAX) NULL,
    [SelectByRouteOptionLabel]                   NVARCHAR (MAX) NULL,
    [EnterFlightNumberOptionLabel]               NVARCHAR (MAX) NULL,
    [ChooseSearchMethodDividerText]              NVARCHAR (MAX) NULL,
    [FlyingFromDefaultText]                      NVARCHAR (MAX) NULL,
    [FlyingToDefaultText]                        NVARCHAR (MAX) NULL,
    [FlightNumberExampleText]                    NVARCHAR (MAX) NULL,
    [FlightResultsHeader]                        NVARCHAR (MAX) NULL,
    [FlightResultsHeaderRouteSeparatorText]      NVARCHAR (MAX) NULL,
    [TimeZoneInformationText]                    NVARCHAR (MAX) NULL,
    [OutboundFlightLabelText]                    NVARCHAR (MAX) NULL,
    [ArrivalFlightLabelText]                     NVARCHAR (MAX) NULL,
    [ScheduledFlightTimeLabelText]               NVARCHAR (MAX) NULL,
    [AcutalFlightTimeLabelText]                  NVARCHAR (MAX) NULL,
    [FlightStatusLabelText]                      NVARCHAR (MAX) NULL,
    [GetFlightInfoButtonLabel]                   NVARCHAR (MAX) NULL,
    [SubmitNotificationRequestButtonLabel]       NVARCHAR (MAX) NULL,
    [NoResultsFound]                             NVARCHAR (MAX) NULL,
    [FlightStatusNotYetDeparted]                 NVARCHAR (MAX) NULL,
    [FlightStatusArrived]                        NVARCHAR (MAX) NULL,
    [FlightStatusDeparted]                       NVARCHAR (MAX) NULL,
    [FlightStatusCancelled]                      NVARCHAR (MAX) NULL,
    [EstimatedLabelText]                         NVARCHAR (MAX) NULL,
    [FlightStatusUnknown]                        NVARCHAR (MAX) NULL,
    [FlightStatusNotificationHeader]             NVARCHAR (MAX) NULL,
    [FlightStatusNotificationMethodInstructions] NVARCHAR (MAX) NULL,
    [FlightStatusNotificationSMSLabel]           NVARCHAR (MAX) NULL,
    [FlightStatusNotificationEmailLabel]         NVARCHAR (MAX) NULL,
    [FlightStatusNotificationSMSInstructions]    NVARCHAR (MAX) NULL,
    [FlightStatusNotificationSMSAreaCodeExample] NVARCHAR (MAX) NULL,
    [WaitingForResultsText]                      NVARCHAR (MAX) NULL,
    [FlightStatusNotificationEmailInstructions]  NVARCHAR (MAX) NULL,
    [FlightStatusNotificationEmailExample]       NVARCHAR (MAX) NULL,
    [LanguageId]                                 INT            NOT NULL,
    [Day]                                        NVARCHAR (MAX) DEFAULT ((0)) NULL,
    [ArrivalNextDay]                             NVARCHAR (MAX) DEFAULT ((0)) NULL,
    [ArrivalNextDayTooltip]                      NVARCHAR (MAX) DEFAULT ((0)) NULL,
    [FlightStatusDiverted]                       NVARCHAR (MAX) NULL,
    [FlightStatusReRouted]                       NVARCHAR (MAX) NULL,
    [FlightStatusForcedReturnRAMP]               NVARCHAR (MAX) NULL,
    [FlightStatusForcedReturnAIR]                NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([FlightStatusLabelsId] ASC)
);





