CREATE TABLE [dbo].[FooterItems] (
    [FooterItemId] INT IDENTITY (1, 1) NOT NULL,
    [LanguageId]   INT NOT NULL,
    PRIMARY KEY CLUSTERED ([FooterItemId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

