CREATE TABLE [dbo].[GeolocatedBannerVersions] (
    [GeolocatedBannerVersionId] INT            IDENTITY (1, 1) NOT NULL,
    [CountryId]                 INT            NOT NULL,
    [Url]                       NVARCHAR (MAX) NULL,
    [Image]                     INT            NULL,
    [StartDate]                 DATETIME2 (7)  NOT NULL,
    [EndDate]                   DATETIME2 (7)  NOT NULL,
    [IsDefault]                 BIT            NOT NULL,
    [ParentId]                  INT            NOT NULL,
    [UrlIdentifier]             NVARCHAR (MAX) NULL,
    [CmsName]                   NVARCHAR (MAX) NULL,
    [Version]                   INT            NOT NULL,
    [IsDraft]                   BIT            NOT NULL,
    [CreatedById]               INT            NULL,
    [CreatedDate]               DATETIME2 (7)  NULL,
    [ApprovedById]              INT            NULL,
    [ApprovedDate]              DATETIME2 (7)  NULL,
    [PublishedById]             INT            NULL,
    [PublishedDate]             DATETIME2 (7)  NULL,
    [UnpublishedById]           INT            NULL,
    [UnpublishedDate]           DATETIME2 (7)  NULL,
    [Url2]                      NVARCHAR (MAX) NULL,
    [Url3]                      NVARCHAR (MAX) NULL,
    [Url4]                      NVARCHAR (MAX) NULL,
    [Url5]                      NVARCHAR (MAX) NULL,
    [Url6]                      NVARCHAR (MAX) NULL,
    [Url7]                      NVARCHAR (MAX) NULL,
    [Url8]                      NVARCHAR (MAX) NULL,
    [Url9]                      NVARCHAR (MAX) NULL,
    [Url10]                     NVARCHAR (MAX) NULL,
    [Image2]                    INT            NULL,
    [Image3]                    INT            NULL,
    [Image4]                    INT            NULL,
    [Image5]                    INT            NULL,
    [Image6]                    INT            NULL,
    [Image7]                    INT            NULL,
    [Image8]                    INT            NULL,
    [Image9]                    INT            NULL,
    [Image10]                   INT            NULL,
    [NewWindow]                 BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow2]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow3]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow4]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow5]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow6]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow7]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow8]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow9]                BIT            DEFAULT ((0)) NOT NULL,
    [NewWindow10]               BIT            DEFAULT ((0)) NOT NULL,
    [CityId]                    INT            NULL,
    PRIMARY KEY CLUSTERED ([GeolocatedBannerVersionId] ASC),
    CONSTRAINT [GeolocatedBannerVersion_ApprovedBy] FOREIGN KEY ([ApprovedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [GeolocatedBannerVersion_CreatedBy] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [GeolocatedBannerVersion_Parent] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[GeolocatedBanners] ([GeolocatedBannerId]),
    CONSTRAINT [GeolocatedBannerVersion_PublishedBy] FOREIGN KEY ([PublishedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [GeolocatedBannerVersion_UnpublishedBy] FOREIGN KEY ([UnpublishedById]) REFERENCES [dbo].[Members] ([Id])
);

