CREATE TABLE [dbo].[IFESSRCodes]
(
    [IFESSRCodeId] INT IDENTITY (1, 1) NOT NULL,
    [IFECode]        NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([IFESSRCodeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

