CREATE TABLE [dbo].[InflightEntertainmentLabels] (
    [InflightEntertainmentLabelsId] INT            IDENTITY (1, 1) NOT NULL,
    [InflightEntertainmentHeading]  NVARCHAR (MAX) NULL,
    [InflightEntertainmentSummary]  NVARCHAR (MAX) NULL,
    [PayMoviesThisMonthTab]         NVARCHAR (MAX) NULL,
    [PayMoviesNextMonthTab]         NVARCHAR (MAX) NULL,
    [PayTvTab]                      NVARCHAR (MAX) NULL,
    [MusicTab]                      NVARCHAR (MAX) NULL,
    [GamesTab]                      NVARCHAR (MAX) NULL,
    [FoodAndDrinkTab]               NVARCHAR (MAX) NULL,
    [DutyFreeTab]                   NVARCHAR (MAX) NULL,
    [MovieTitleColumnHeader]        NVARCHAR (MAX) NULL,
    [MovieGenreColumnHeader]        NVARCHAR (MAX) NULL,
    [MovieCastColumnHeader]         NVARCHAR (MAX) NULL,
    [MovieRunningTimeColumnHeader]  NVARCHAR (MAX) NULL,
    [MovieTrailerColumnHeader]      NVARCHAR (MAX) NULL,
    [MovieFeeColumnHeader]          NVARCHAR (MAX) NULL,
    [Rating]                        NVARCHAR (MAX) NULL,
    [Director]                      NVARCHAR (MAX) NULL,
    [MovieLanguage]                 NVARCHAR (MAX) NULL,
    [Cast]                          NVARCHAR (MAX) NULL,
    [Year]                          NVARCHAR (MAX) NULL,
    [Genre]                         NVARCHAR (MAX) NULL,
    [Synopsis]                      NVARCHAR (MAX) NULL,
    [NoMoviesText]                  NVARCHAR (MAX) NULL,
    [MovieRunningTimeInMinutes]     NVARCHAR (MAX) NULL,
    [WatchTrailer]                  NVARCHAR (MAX) NULL,
    [NoResultsText]                 NVARCHAR (MAX) NULL,
    [PayMoviesCurrency]             NVARCHAR (MAX) NULL,
    [LanguageId]                    INT            NOT NULL,
    [MoviesThisMonth]               NVARCHAR (MAX) NULL,
    [NewsPaperTab]                  NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([InflightEntertainmentLabelsId] ASC)
);



