CREATE TABLE [dbo].[InflightMovieVersions] (
    [InflightMovieVersionId] INT             IDENTITY (1, 1) NOT NULL,
    [Title]                  NVARCHAR (MAX)  NULL,
    [Genre]                  NVARCHAR (MAX)  NULL,
    [Cast]                   NVARCHAR (MAX)  NULL,
    [RunningTime]            INT             NOT NULL,
    [TrailerUrl]             NVARCHAR (MAX)  NULL,
    [Fee]                    DECIMAL (18, 2) NOT NULL,
    [StartDate]              DATETIME2 (7)   NULL,
    [EndDate]                DATETIME2 (7)   NULL,
    [Director]               NVARCHAR (MAX)  NULL,
    [Year]                   INT             NOT NULL,
    [Rating]                 NVARCHAR (MAX)  NULL,
    [Language]               NVARCHAR (MAX)  NULL,
    [Synopsis]               NVARCHAR (MAX)  NULL,
    [ParentId]               INT             NOT NULL,
    [UrlIdentifier]          NVARCHAR (MAX)  NULL,
    [CmsName]                NVARCHAR (MAX)  NULL,
    [Version]                INT             NOT NULL,
    [IsDraft]                BIT             NOT NULL,
    [CreatedById]            INT             NULL,
    [CreatedDate]            DATETIME2 (7)   NULL,
    [ApprovedById]           INT             NULL,
    [ApprovedDate]           DATETIME2 (7)   NULL,
    [PublishedById]          INT             NULL,
    [PublishedDate]          DATETIME2 (7)   NULL,
    [UnpublishedById]        INT             NULL,
    [UnpublishedDate]        DATETIME2 (7)   NULL,
    [IsNewMovie]             BIT             NULL,
    [NewMovieSortOrder]      INT             NULL,
    [ImagePath]              NVARCHAR (MAX)  NULL,
    [Image]                  INT             NULL,
    PRIMARY KEY CLUSTERED ([InflightMovieVersionId] ASC),
    CONSTRAINT [InflightMovieVersion_ApprovedBy] FOREIGN KEY ([ApprovedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [InflightMovieVersion_CreatedBy] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [InflightMovieVersion_Parent] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[InflightMovies] ([InflightMovieId]),
    CONSTRAINT [InflightMovieVersion_PublishedBy] FOREIGN KEY ([PublishedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [InflightMovieVersion_UnpublishedBy] FOREIGN KEY ([UnpublishedById]) REFERENCES [dbo].[Members] ([Id])
);



