CREATE TABLE [dbo].[MemberRole] (
    [MemberId] INT NOT NULL,
    [RoleId]   INT NOT NULL,
    PRIMARY KEY CLUSTERED ([MemberId] ASC, [RoleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

