CREATE TABLE [dbo].[MobilePaymentLabels] (
    [Language]                               NVARCHAR (128) NOT NULL,
    [Payment]                                NVARCHAR (MAX) NULL,
    [DoNotAcceptCardsFromCountries]          NVARCHAR (MAX) NULL,
    [PayNow]                                 NVARCHAR (MAX) NULL,
    [OnlyTakesAMinute]                       NVARCHAR (MAX) NULL,
    [SafeAndSecure]                          NVARCHAR (MAX) NULL,
    [GuaranteeYourFlight]                    NVARCHAR (MAX) NULL,
    [PayLater]                               NVARCHAR (MAX) NULL,
    [SomeElseCanPay]                         NVARCHAR (MAX) NULL,
    [EasyAndStraightforward]                 NVARCHAR (MAX) NULL,
    [ReservesTicket]                         NVARCHAR (MAX) NULL,
    [Includes]                               NVARCHAR (MAX) NULL,
    [HandBaggage]                            NVARCHAR (MAX) NULL,
    [CheckedBaggage]                         NVARCHAR (MAX) NULL,
    [Seats]                                  NVARCHAR (MAX) NULL,
    [Insurance]                              NVARCHAR (MAX) NULL,
    [AllPassengersOnAllJourneys]             NVARCHAR (MAX) NULL,
    [HaveAVoucher]                           NVARCHAR (MAX) NULL,
    [VoucherRef]                             NVARCHAR (MAX) NULL,
    [VoucherPin]                             NVARCHAR (MAX) NULL,
    [UseVoucher]                             NVARCHAR (MAX) NULL,
    [PaymentDetails]                         NVARCHAR (MAX) NULL,
    [CardType]                               NVARCHAR (MAX) NULL,
    [CardNumber]                             NVARCHAR (MAX) NULL,
    [FirstNameOnCard]                        NVARCHAR (MAX) NULL,
    [LastNameOnCard]                         NVARCHAR (MAX) NULL,
    [ExpiryDate]                             NVARCHAR (MAX) NULL,
    [CVVNumber]                              NVARCHAR (MAX) NULL,
    [Last3Numbers]                           NVARCHAR (MAX) NULL,
    [TotalDueForthisBooking]                 NVARCHAR (MAX) NULL,
    [Voucher]                                NVARCHAR (MAX) NULL,
    [Value]                                  NVARCHAR (MAX) NULL,
    [BalanceRemaining]                       NVARCHAR (MAX) NULL,
    [TheVoucherWillbeAppliedOnlyWhen]        NVARCHAR (MAX) NULL,
    [IHaveReadTerms]                         NVARCHAR (MAX) NULL,
    [TermsAndConditions]                     NVARCHAR (MAX) NULL,
    [BookFlight]                             NVARCHAR (MAX) NULL,
    [IfYouPayByCcCopy]                       NVARCHAR (MAX) NULL,
    [PayLaterCopy]                           NVARCHAR (MAX) NULL,
    [YourBookingWillBeCancelled]             NVARCHAR (MAX) NULL,
    [BackToTop]                              NVARCHAR (MAX) NULL,
    [OnVoucher]                              NVARCHAR (MAX) NULL,
    [HowWouldYouLikeToPayOutstandingBalance] NVARCHAR (MAX) NULL,
    [ExpiryDateYear]                         NVARCHAR (MAX) NULL,
    [BillingAddress]                         NVARCHAR (MAX) NULL,
    [AddressLine1]                           NVARCHAR (MAX) NULL,
    [AddressLine2]                           NVARCHAR (MAX) NULL,
    [CityTown]                               NVARCHAR (MAX) NULL,
    [StateUsAndCanadaOnly]                   NVARCHAR (MAX) NULL,
    [ZipCodeUsAndCanadaOnly]                 NVARCHAR (MAX) NULL,
    [Country]                                NVARCHAR (MAX) NULL,
    [IfACreditCardIsUsedToPayOnBehalfCopy]   NVARCHAR (MAX) NULL,
    [TotalAmountToBeChargedToYourCreditCard] NVARCHAR (MAX) NULL,
    [Pay]                                    NVARCHAR (MAX) NULL,
    [IncludingCreditCardFeeOf]               NVARCHAR (MAX) NULL,
    [BillingCountryDefaultText]              NVARCHAR (MAX) NULL,
    [CardTypeDefaultText]                    NVARCHAR (MAX) NULL,
    [BillingStateDefaultText]                NVARCHAR (MAX) NULL,
    [TermsAndConditionsLinkUrl]              NVARCHAR (MAX) CONSTRAINT [DF_MobilePaymentLabels_TermsAndConditionsLinkUrl] DEFAULT ('#') NOT NULL,
    [YourBookingWillBeCancelled72]           NVARCHAR (MAX) NULL,
    [Hour]                                   NVARCHAR (MAX) NULL,
    [Minute]                                 NVARCHAR (MAX) NULL,
    [Minutes]                                NVARCHAR (MAX) NULL,
    [And]                                    NVARCHAR (MAX) NULL,
    [MobileRefreshAlert]                     NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);







