CREATE TABLE [dbo].[MobileOptionalExtrasLabels] (
    [Language]                               NVARCHAR (128) NOT NULL,
    [OptionalExtras]                         NVARCHAR (MAX) NULL,
    [FlightAndExtras]                        NVARCHAR (MAX) NULL,
    [PrimaryPassenger]                       NVARCHAR (MAX) NULL,
    [NeedExtraBaggageAllowance]              NVARCHAR (MAX) NULL,
    [EachMemberOfYourParty]                  NVARCHAR (MAX) NULL,
    [kg]                                     NVARCHAR (MAX) NULL,
    [CheckedBaggage]                         NVARCHAR (MAX) NULL,
    [ChildrenYoungerThan2YearsNoBaggage]     NVARCHAR (MAX) NULL,
    [TotalIncHandBaggage]                    NVARCHAR (MAX) NULL,
    [WhereDoYouWantToSitGoingOut]            NVARCHAR (MAX) NULL,
    [WhereDoYouWantToSitReturn]              NVARCHAR (MAX) NULL,
    [AllocationAtCheckIn]                    NVARCHAR (MAX) NULL,
    [SeatMap]                                NVARCHAR (MAX) NULL,
    [Surcharge]                              NVARCHAR (MAX) NULL,
    [Exit]                                   NVARCHAR (MAX) NULL,
    [YesInsuranceRequired]                   NVARCHAR (MAX) NULL,
    [ForEachPassengerCancellationMedicalEtc] NVARCHAR (MAX) NULL,
    [NoBaggage]                              NVARCHAR (MAX) NULL,
    [BackToTop]                              NVARCHAR (MAX) NULL,
    [SkipSeats]                              NVARCHAR (MAX) NULL,
    [Aisle]                                  NVARCHAR (MAX) NULL,
    [Window]                                 NVARCHAR (MAX) NULL,
    [Seat]                                   NVARCHAR (MAX) NULL,
    [Row]                                    NVARCHAR (MAX) NULL,
    [ChildrenYoungerThan2YearsNoSeats]       NVARCHAR (MAX) NULL,
    [SkipBaggage]                            NVARCHAR (MAX) NULL,
    [UseTheMenusAboveToSelect]               NVARCHAR (MAX) NULL,
    [NoInsurance]                            NVARCHAR (MAX) NULL,
    [ViewTheSeatingDiagramBelow]             NVARCHAR (MAX) NULL,
    [Only]                                   NVARCHAR (MAX) NULL,
    [BagsLeftAt]                             NVARCHAR (MAX) NULL,
    [ResetAllSeats]                          NVARCHAR (MAX) NULL,
    [NoExtraBaggageDropDownOption]           NVARCHAR (MAX) NULL,
    [IncludedExtraBaggageDropDownOption]     NVARCHAR (MAX) NULL,
    [AddExtraBaggageDropDownOption]          NVARCHAR (MAX) NULL,
    [SkipMeal]                               NVARCHAR (MAX) NULL,
    [BuyMealForTheJourney]                   NVARCHAR (MAX) NULL,
    [NoMealRequired]                         NVARCHAR (MAX) NULL,
    [NoDietary]                              NVARCHAR (MAX) NULL,
    [ChildrenYoungerThan2YearsNoMeal]        NVARCHAR (MAX) NULL,
    [MealSubHdrTxt]                          NVARCHAR (MAX) NULL,
    [BuyMealOnBoard]                         NVARCHAR (MAX) NULL,
    [SeatSelection]                          NVARCHAR (MAX) NULL,
    [BaggageAllowance]                       NVARCHAR (MAX) NULL,
    [BusinessHeadingOverSeatImage]           NVARCHAR (MAX) NULL,
    [Free]                                   NVARCHAR (MAX) NULL,
    [HandBaggage]                            NVARCHAR (MAX) NULL,
    [ProtectYourselfOnYourTrip]              NVARCHAR (100) NULL,
    [PreselectInsuranceMessageMobile]        NVARCHAR (500) NULL,
    [IncludedMeals]                          NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);







