CREATE TABLE [dbo].[MobileConfirmationLabels] (
    [Language]                            NVARCHAR (128) NOT NULL,
    [YourBookingRef]                      NVARCHAR (MAX) NULL,
    [YourPaymentRef]                      NVARCHAR (MAX) NULL,
    [AnEmailHasBeenSent]                  NVARCHAR (MAX) NULL,
    [TotalCost]                           NVARCHAR (MAX) NULL,
    [Fligts]                              NVARCHAR (MAX) NULL,
    [BaggageTotal]                        NVARCHAR (MAX) NULL,
    [SeatingTotal]                        NVARCHAR (MAX) NULL,
    [Insurance]                           NVARCHAR (MAX) NULL,
    [CCFee]                               NVARCHAR (MAX) NULL,
    [Taxes]                               NVARCHAR (MAX) NULL,
    [PromoDiscount]                       NVARCHAR (MAX) NULL,
    [TotalPayment]                        NVARCHAR (MAX) NULL,
    [YourJourney]                         NVARCHAR (MAX) NULL,
    [YourBookingIsHeld]                   NVARCHAR (MAX) NULL,
    [ToCompleteTheBooking]                NVARCHAR (MAX) NULL,
    [LocateNearsetPaymentPoint]           NVARCHAR (MAX) NULL,
    [BackToTop]                           NVARCHAR (MAX) NULL,
    [BookingHeldFor48Hours]               NVARCHAR (MAX) NULL,
    [PleaseArriveAtLeast]                 NVARCHAR (MAX) NULL,
    [ThreeHours]                          NVARCHAR (MAX) NULL,
    [BeforeYourFlightToAllowForCheckIn]   NVARCHAR (MAX) NULL,
    [PaymentDue]                          NVARCHAR (MAX) NULL,
    [HandBaggage]                         NVARCHAR (MAX) NULL,
    [CheckedBaggage]                      NVARCHAR (MAX) NULL,
    [kg]                                  NVARCHAR (MAX) NULL,
    [Seat]                                NVARCHAR (MAX) NULL,
    [Home]                                NVARCHAR (MAX) NULL,
    [SorryUnableToMakeBooking]            NVARCHAR (MAX) NULL,
    [ContactUs]                           NVARCHAR (MAX) NULL,
    [SeatsNoLongerAvailable]              NVARCHAR (MAX) NULL,
    [SelectDifferentSeats]                NVARCHAR (MAX) NULL,
    [OrYouCanContinueBookingWithout]      NVARCHAR (MAX) NULL,
    [ChoosingToPayLaterRequires]          NVARCHAR (MAX) NULL,
    [FortyEightHours]                     NVARCHAR (MAX) NULL,
    [AtAPaymentPoint]                     NVARCHAR (MAX) NULL,
    [FlightNoLongerAvailable]             NVARCHAR (MAX) NULL,
    [SorryButWhileYouWereSelecting]       NVARCHAR (MAX) NULL,
    [ThisCanHappen]                       NVARCHAR (MAX) NULL,
    [SelectAlternativeFlight]             NVARCHAR (MAX) NULL,
    [StartAgain]                          NVARCHAR (MAX) NULL,
    [SelectDifferentMeals]                NVARCHAR (MAX) NULL,
    [OrYouCanContinueBookingWithoutMeals] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);



