CREATE TABLE [dbo].[MobileCommonLabels] (
    [Language]                 NVARCHAR (128) NOT NULL,
    [Hi]                       NVARCHAR (MAX) NULL,
    [LogIn]                    NVARCHAR (MAX) NULL,
    [LogOut]                   NVARCHAR (MAX) NULL,
    [Flight]                   NVARCHAR (MAX) NULL,
    [Departing]                NVARCHAR (MAX) NULL,
    [Returning]                NVARCHAR (MAX) NULL,
    [Outbound]                 NVARCHAR (MAX) NULL,
    [Return]                   NVARCHAR (MAX) NULL,
    [To]                       NVARCHAR (MAX) NULL,
    [Total]                    NVARCHAR (MAX) NULL,
    [InclusiveOfAllTaxes]      NVARCHAR (MAX) NULL,
    [Adult]                    NVARCHAR (MAX) NULL,
    [Adults]                   NVARCHAR (MAX) NULL,
    [Child]                    NVARCHAR (MAX) NULL,
    [Children]                 NVARCHAR (MAX) NULL,
    [Infant]                   NVARCHAR (MAX) NULL,
    [Infants]                  NVARCHAR (MAX) NULL,
    [NoChange]                 NVARCHAR (MAX) NULL,
    [PayToChange]              NVARCHAR (MAX) NULL,
    [FreeToChange]             NVARCHAR (MAX) NULL,
    [Fare]                     NVARCHAR (MAX) NULL,
    [Arrives]                  NVARCHAR (MAX) NULL,
    [Departs]                  NVARCHAR (MAX) NULL,
    [DirectFlight]             NVARCHAR (MAX) NULL,
    [Duration]                 NVARCHAR (MAX) NULL,
    [Dur]                      NVARCHAR (MAX) NULL,
    [Stop]                     NVARCHAR (MAX) NULL,
    [Continue]                 NVARCHAR (MAX) NULL,
    [Back]                     NVARCHAR (MAX) NULL,
    [SelectAlternativeFlights] NVARCHAR (MAX) NULL,
    [StartAgain]               NVARCHAR (MAX) NULL,
    [ContactUs]                NVARCHAR (MAX) NULL,
    [PrimaryPassenger]         NVARCHAR (MAX) NULL,
    [Day]                      NVARCHAR (MAX) NULL,
    [On]                       NVARCHAR (MAX) NULL,
    [Edit]                     NVARCHAR (MAX) NULL,
    [BackToTop]                NVARCHAR (MAX) NULL,
    [FareLower]                NVARCHAR (MAX) NOT NULL,
    [BuyMealOnBoard]           NVARCHAR (MAX) NULL,
    [BusinessBasic]            NVARCHAR (MAX) NULL,
    [Cabin]                    NVARCHAR (MAX) NULL,
    [Includes]                 NVARCHAR (MAX) NULL,
    [MetroStatusSearchError]   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);





