CREATE TABLE [dbo].[MobileNonBookingLabels] (
    [Language]                         NVARCHAR (128) NOT NULL,
    [FlightNumber]                     NVARCHAR (MAX) NULL,
    [Route]                            NVARCHAR (MAX) NULL,
    [DueToArrive]                      NVARCHAR (MAX) NULL,
    [FlyingFrom]                       NVARCHAR (MAX) NULL,
    [FlyingTo]                         NVARCHAR (MAX) NULL,
    [GetFlightInfo]                    NVARCHAR (MAX) NULL,
    [BackToTop]                        NVARCHAR (MAX) NULL,
    [CheckFlightStatus]                NVARCHAR (MAX) NULL,
    [FlightSearch]                     NVARCHAR (MAX) NULL,
    [Flights]                          NVARCHAR (MAX) NULL,
    [BasedOn24HourClock]               NVARCHAR (MAX) NULL,
    [AllTimesAreShownLocal]            NVARCHAR (MAX) NULL,
    [Scheduled]                        NVARCHAR (MAX) NULL,
    [Expected]                         NVARCHAR (MAX) NULL,
    [Terminal]                         NVARCHAR (MAX) NULL,
    [Status]                           NVARCHAR (MAX) NULL,
    [Arrived]                          NVARCHAR (MAX) NULL,
    [NotYetArrived]                    NVARCHAR (MAX) NULL,
    [FlightStatusTop]                  NVARCHAR (MAX) NULL,
    [FlydubaiTimetable]                NVARCHAR (MAX) NULL,
    [RoundTrip]                        NVARCHAR (MAX) NULL,
    [OneWay]                           NVARCHAR (MAX) NULL,
    [OutboundDate]                     NVARCHAR (MAX) NULL,
    [ReturnDate]                       NVARCHAR (MAX) NULL,
    [ShowTimetable]                    NVARCHAR (MAX) NULL,
    [EffectiveBetween]                 NVARCHAR (MAX) NULL,
    [Arrival]                          NVARCHAR (MAX) NULL,
    [TimetableTop]                     NVARCHAR (MAX) NULL,
    [ContactUs]                        NVARCHAR (MAX) NULL,
    [WhereAreYouCallingFrom]           NVARCHAR (MAX) NULL,
    [GetContactNumber]                 NVARCHAR (MAX) NULL,
    [EmailUs]                          NVARCHAR (MAX) NULL,
    [flydubaiEmailAddress]             NVARCHAR (MAX) NULL,
    [ContactUsTop]                     NVARCHAR (MAX) NULL,
    [flydubaiContactNumber]            NVARCHAR (MAX) NULL,
    [flydubaiCallCentre]               NVARCHAR (MAX) NULL,
    [TravelPartners]                   NVARCHAR (MAX) NULL,
    [OurTravelPartnersAreAbleToAssist] NVARCHAR (MAX) NULL,
    [SearchAgain]                      NVARCHAR (MAX) NULL,
    [MyBookings]                       NVARCHAR (MAX) NULL,
    [Record]                           NVARCHAR (MAX) NULL,
    [Paid]                             NVARCHAR (MAX) NULL,
    [Pending]                          NVARCHAR (MAX) NULL,
    [TimeUntilExpiry]                  NVARCHAR (MAX) NULL,
    [View]                             NVARCHAR (MAX) NULL,
    [BookingsTop]                      NVARCHAR (MAX) NULL,
    [Completed]                        NVARCHAR (MAX) NULL,
    [ExpiredCancelled]                 NVARCHAR (MAX) NULL,
    [FiveMostRecentBoookings]          NVARCHAR (MAX) NULL,
    [XMostRecentBookings]              NVARCHAR (MAX) NULL,
    [ActualDeparture]                  NVARCHAR (MAX) NULL,
    [ActualArrival]                    NVARCHAR (MAX) NULL,
    [EstimatedDeparture]               NVARCHAR (MAX) NULL,
    [EstimatedArrival]                 NVARCHAR (MAX) NULL,
    [ScheduledDeparture]               NVARCHAR (MAX) NULL,
    [AtPaymentPointToKeepFare]         NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);





