CREATE TABLE [dbo].[MobilePassengerLabels] (
    [Language]                               NVARCHAR (128) NOT NULL,
    [PassengerDetails]                       NVARCHAR (MAX) NULL,
    [FlightsAndExtras]                       NVARCHAR (MAX) NULL,
    [HaveAFlydubaiAccount]                   NVARCHAR (MAX) NULL,
    [YourDetailsWillBeFilledInAutomatically] NVARCHAR (MAX) NULL,
    [LoginAsFlydubaiMember]                  NVARCHAR (MAX) NULL,
    [AdultPassenger]                         NVARCHAR (MAX) NULL,
    [PrimaryPassenger]                       NVARCHAR (MAX) NULL,
    [ChildPassenger]                         NVARCHAR (MAX) NULL,
    [InfantPassenger]                        NVARCHAR (MAX) NULL,
    [Passenger]                              NVARCHAR (MAX) NULL,
    [YourDetails]                            NVARCHAR (MAX) NULL,
    [Title]                                  NVARCHAR (MAX) NULL,
    [FirstName]                              NVARCHAR (MAX) NULL,
    [LastName]                               NVARCHAR (MAX) NULL,
    [EmailAddress]                           NVARCHAR (MAX) NULL,
    [PreferredContactNumber]                 NVARCHAR (MAX) NULL,
    [CountryCode]                            NVARCHAR (MAX) NULL,
    [AreaCode]                               NVARCHAR (MAX) NULL,
    [PhoneNumber]                            NVARCHAR (MAX) NULL,
    [DateOfBirth]                            NVARCHAR (MAX) NULL,
    [AssignInfantTo]                         NVARCHAR (MAX) NULL,
    [ContactNumber]                          NVARCHAR (MAX) NULL,
    [Edit]                                   NVARCHAR (MAX) NULL,
    [BackToTop]                              NVARCHAR (MAX) NULL,
    [TitleDropDownDefaultText]               NVARCHAR (MAX) NULL,
    [CountryCodeDefaultText]                 NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

