CREATE TABLE [dbo].[NewsArticleVersions] (
    [NewsArticleVersionId] INT            IDENTITY (1, 1) NOT NULL,
    [NewsArticleDate]      DATETIME2 (7)  NOT NULL,
    [Title]                NVARCHAR (MAX) NULL,
    [SummaryHtml]          NVARCHAR (MAX) NULL,
    [BodyHtml]             NVARCHAR (MAX) NULL,
    [ThumbnailImage]       INT            NULL,
    [Image]                INT            NULL,
    [ImageCaption]         NVARCHAR (MAX) NULL,
    [VideoTitle]           NVARCHAR (MAX) NULL,
    [VideoUrl]             NVARCHAR (MAX) NULL,
    [ParentId]             INT            NOT NULL,
    [UrlIdentifier]        NVARCHAR (MAX) NULL,
    [CmsName]              NVARCHAR (MAX) NULL,
    [Version]              INT            NOT NULL,
    [IsDraft]              BIT            NOT NULL,
    [CreatedById]          INT            NULL,
    [CreatedDate]          DATETIME2 (7)  NULL,
    [ApprovedById]         INT            NULL,
    [ApprovedDate]         DATETIME2 (7)  NULL,
    [PublishedById]        INT            NULL,
    [PublishedDate]        DATETIME2 (7)  NULL,
    [UnpublishedById]      INT            NULL,
    [UnpublishedDate]      DATETIME2 (7)  NULL,
    PRIMARY KEY CLUSTERED ([NewsArticleVersionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

