CREATE TABLE [dbo].[NewsArticleLabels] (
    [NewsArticleLabelsId]        INT            IDENTITY (1, 1) NOT NULL,
    [ArticleTitle]               NVARCHAR (MAX) NULL,
    [LargeModuleTitle]           NVARCHAR (MAX) NULL,
    [SmallModuleTitle]           NVARCHAR (MAX) NULL,
    [SmallModuleSeeAllNews]      NVARCHAR (MAX) NULL,
    [BackToList]                 NVARCHAR (MAX) NULL,
    [LargeModuleSeeAllLink]      NVARCHAR (MAX) NULL,
    [LargeModuleReadMore]        NVARCHAR (MAX) NULL,
    [SmallModuleReadMore]        NVARCHAR (MAX) NULL,
    [MoreLikeThis]               NVARCHAR (MAX) NULL,
    [PageNumberOfTotal]          NVARCHAR (MAX) NULL,
    [PaginationNext]             NVARCHAR (MAX) NULL,
    [PaginationPrevious]         NVARCHAR (MAX) NULL,
    [NoNewsText]                 NVARCHAR (MAX) NULL,
    [NewsArchiveTitle]           NVARCHAR (MAX) NULL,
    [SelectMonth]                NVARCHAR (MAX) NULL,
    [SelectYear]                 NVARCHAR (MAX) NULL,
    [NewsArchiveSearch]          NVARCHAR (MAX) NULL,
    [ListModuleTitle]            NVARCHAR (MAX) NULL,
    [RelatedArticlesPageTitle]   NVARCHAR (MAX) NULL,
    [RelatedArticlesModuleTitle] NVARCHAR (MAX) NULL,
    [RssFeedTitle]               NVARCHAR (MAX) NULL,
    [RssFeedDescription]         NVARCHAR (MAX) NULL,
    [ClickImageToOpenVideoText]  NVARCHAR (MAX) NULL,
    [LanguageId]                 INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([NewsArticleLabelsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

