CREATE TABLE [dbo].[PassengerDetailsLabels] (
    [Language]                                                                   NVARCHAR (128) NOT NULL,
    [DateOfBirthIsInvalid]                                                       NVARCHAR (MAX) NULL,
    [InfantIsNotAssignedToAnAdult]                                               NVARCHAR (MAX) NULL,
    [AdultHasMoreThanOnInfantAssigned]                                           NVARCHAR (MAX) NULL,
    [AreaCode]                                                                   NVARCHAR (MAX) NULL,
    [Number]                                                                     NVARCHAR (MAX) NULL,
    [PleaseCheckTheseDetailsAreCorrect]                                          NVARCHAR (MAX) NULL,
    [ImNewToFlydubai]                                                            NVARCHAR (MAX) NULL,
    [IHaveAFlydubaiAccount]                                                      NVARCHAR (MAX) NULL,
    [FieldsMarked]                                                               NVARCHAR (MAX) NULL,
    [AreMandatory]                                                               NVARCHAR (MAX) NULL,
    [AssignInfantTo]                                                             NVARCHAR (MAX) NULL,
    [Email]                                                                      NVARCHAR (MAX) NULL,
    [HomeNumber]                                                                 NVARCHAR (MAX) NULL,
    [MobileNumber]                                                               NVARCHAR (MAX) NULL,
    [WhyAreWeAskingForTheseNumbers]                                              NVARCHAR (MAX) NULL,
    [WhyAreWeAskingForTheseNumbersTooltip]                                       NVARCHAR (MAX) NULL,
    [PreferedContactNumber]                                                      NVARCHAR (MAX) NULL,
    [CountryCodeForOtherPhone]                                                   NVARCHAR (MAX) NULL,
    [IWouldLikeToCreateAnAccount]                                                NVARCHAR (MAX) NULL,
    [Password]                                                                   NVARCHAR (MAX) NULL,
    [PasswordTooltip]                                                            NVARCHAR (MAX) NULL,
    [ConfirmPassword]                                                            NVARCHAR (MAX) NULL,
    [IWouldLikeToSubscribeToFlydubaiOffers]                                      NVARCHAR (MAX) NULL,
    [SubscribeMeToFlydubaiOffers]                                                NVARCHAR (MAX) NULL,
    [IWantToReceiveOffersIn]                                                     NVARCHAR (MAX) NULL,
    [OffersFrom]                                                                 NVARCHAR (MAX) NULL,
    [ViaSMS]                                                                     NVARCHAR (MAX) NULL,
    [ViaEmail]                                                                   NVARCHAR (MAX) NULL,
    [English]                                                                    NVARCHAR (MAX) NULL,
    [Arabic]                                                                     NVARCHAR (MAX) NULL,
    [AllCountries]                                                               NVARCHAR (MAX) NULL,
    [ShowOptions]                                                                NVARCHAR (MAX) NULL,
    [SameAs]                                                                     NVARCHAR (MAX) NULL,
    [Mobile]                                                                     NVARCHAR (MAX) NULL,
    [Home]                                                                       NVARCHAR (MAX) NULL,
    [Other]                                                                      NVARCHAR (MAX) NULL,
    [Title]                                                                      NVARCHAR (MAX) NULL,
    [FirstName]                                                                  NVARCHAR (MAX) NULL,
    [LastName]                                                                   NVARCHAR (MAX) NULL,
    [AdultPassenger]                                                             NVARCHAR (MAX) NULL,
    [ChildPassenger]                                                             NVARCHAR (MAX) NULL,
    [InfantPassenger]                                                            NVARCHAR (MAX) NULL,
    [PrimaryPassenger]                                                           NVARCHAR (MAX) NULL,
    [DateOfBirth]                                                                NVARCHAR (MAX) NULL,
    [Yyyy]                                                                       NVARCHAR (MAX) NULL,
    [Mm]                                                                         NVARCHAR (MAX) NULL,
    [Dd]                                                                         NVARCHAR (MAX) NULL,
    [Select]                                                                     NVARCHAR (MAX) NULL,
    [EnterFirstName]                                                             NVARCHAR (MAX) NULL,
    [EnterLastName]                                                              NVARCHAR (MAX) NULL,
    [EnterMiddleName]                                                            NVARCHAR (MAX) NULL,
    [EnterEmail]                                                                 NVARCHAR (MAX) NULL,
    [CountryCode]                                                                NVARCHAR (MAX) NULL,
    [EnterPassword]                                                              NVARCHAR (MAX) NULL,
    [HideOptions]                                                                NVARCHAR (MAX) NULL,
    [TelephoneNumbers]                                                           NVARCHAR (MAX) NULL,
    [AdultTitles]                                                                NVARCHAR (MAX) NULL,
    [ChildTitles]                                                                NVARCHAR (MAX) NULL,
    [MiddleName]                                                                 NVARCHAR (MAX) NULL,
    [AdvancedPassengerInformation]                                               NVARCHAR (MAX) NULL,
    [PleaseSelect]                                                               NVARCHAR (MAX) NULL,
    [PassportNumber]                                                             NVARCHAR (MAX) NULL,
    [InvalidPassportNumber]                                                      NVARCHAR (MAX) NULL,
    [IssuingCountry]                                                             NVARCHAR (MAX) NULL,
    [Nationality]                                                                NVARCHAR (MAX) NULL,
    [ExpiryDate]                                                                 NVARCHAR (MAX) NULL,
    [Month]                                                                      NVARCHAR (MAX) NULL,
    [Year]                                                                       NVARCHAR (MAX) NULL,
    [TheExpiryDateCannotBeInThePast]                                             NVARCHAR (MAX) NULL,
    [Male]                                                                       NVARCHAR (MAX) NULL,
    [Female]                                                                     NVARCHAR (MAX) NULL,
    [IConfirmThatTheTravelDocumentInformationProvidedAboveIsCorrect]             NVARCHAR (MAX) NULL,
    [SaveChanges]                                                                NVARCHAR (MAX) NULL,
    [CancelChanges]                                                              NVARCHAR (MAX) NULL,
    [Gender]                                                                     NVARCHAR (MAX) NULL,
    [AddBaggage]                                                                 NVARCHAR (MAX) NULL,
    [AddSeat]                                                                    NVARCHAR (MAX) NULL,
    [NoInsurance]                                                                NVARCHAR (MAX) NULL,
    [Name]                                                                       NVARCHAR (MAX) NULL,
    [EmailAddress]                                                               NVARCHAR (MAX) NULL,
    [MobileContactNumber]                                                        NVARCHAR (MAX) NULL,
    [AdditionalInformationIsRequiredForYourFlightYouCanSaveTimeByEnteringItHere] NVARCHAR (MAX) NULL,
    [Passenger]                                                                  NVARCHAR (MAX) NULL,
    [Selection]                                                                  NVARCHAR (MAX) NULL,
    [Remove]                                                                     NVARCHAR (MAX) NULL,
    [Adult]                                                                      NVARCHAR (MAX) NULL,
    [Child]                                                                      NVARCHAR (MAX) NULL,
    [Continue]                                                                   NVARCHAR (MAX) NULL,
    [WarningTextForExistingSpecialOffersSubscribers]                             NVARCHAR (MAX) NULL,
    [PasswordTooltipHeading]                                                     NVARCHAR (MAX) NULL,
    [InFlightEntertainment]                                                      NVARCHAR (MAX) NULL,
    [AddInFlightEntertainment]                                                   NVARCHAR (MAX) NULL,
    [Russian]                                                                    NVARCHAR (MAX) NULL,
    [AddMeal]                                                                    NVARCHAR (MAX) NULL,
    [APISTooltipContent]                                                         VARCHAR (MAX)  NULL,
    [MakeChangesToTheCompleteAdvancedPassengerInformation]                       VARCHAR (MAX)  NULL,
    [Country]                                                                    NVARCHAR (MAX) NULL,
    [PassengerContactDetails]                                                    NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);









