CREATE TABLE [dbo].[PaymentLabels] (
    [Language]                                                 NVARCHAR (128) NOT NULL,
    [PleaseCheckDetailsAreCorrect]                             NVARCHAR (MAX) NULL,
    [SorryHavingTroubleProcessingYourPayment]                  NVARCHAR (MAX) NULL,
    [DontWorryTryAgainOrPayLater]                              NVARCHAR (MAX) NULL,
    [UnfortunaltelySeatsYouSelectedNoLongerAvailable]          NVARCHAR (MAX) NULL,
    [YouCanEitherContinueReducedCostOf]                        NVARCHAR (MAX) NULL,
    [YourFlightWithoutSeatReservationsOr]                      NVARCHAR (MAX) NULL,
    [SelectAlternativeSeats]                                   NVARCHAR (MAX) NULL,
    [PayNow]                                                   NVARCHAR (MAX) NULL,
    [PayLater]                                                 NVARCHAR (MAX) NULL,
    [PayNowBenefitOne]                                         NVARCHAR (MAX) NULL,
    [PayNowBenefitTwo]                                         NVARCHAR (MAX) NULL,
    [PayNowBenefitThree]                                       NVARCHAR (MAX) NULL,
    [PaymentDetails]                                           NVARCHAR (MAX) NULL,
    [FieldsMarked]                                             NVARCHAR (MAX) NULL,
    [AreMandatory]                                             NVARCHAR (MAX) NULL,
    [PaymentMethod]                                            NVARCHAR (MAX) NULL,
    [DebitCardCreditCard]                                      NVARCHAR (MAX) NULL,
    [Voucher]                                                  NVARCHAR (MAX) NULL,
    [AvailableCredit]                                          NVARCHAR (MAX) NULL,
    [IsTheCardVoucherHolderTravelling]                         NVARCHAR (MAX) NULL,
    [IfYouPayWithCreditCardFlyDubaiWillAskToSeeIt]             NVARCHAR (MAX) NULL,
    [Yes]                                                      NVARCHAR (MAX) NULL,
    [No]                                                       NVARCHAR (MAX) NULL,
    [BillingCountry]                                           NVARCHAR (MAX) NULL,
    [CountryOfBillingAddress]                                  NVARCHAR (MAX) NULL,
    [CardType]                                                 NVARCHAR (MAX) NULL,
    [CardNumber]                                               NVARCHAR (MAX) NULL,
    [FirstName]                                                NVARCHAR (MAX) NULL,
    [LastName]                                                 NVARCHAR (MAX) NULL,
    [ExpiryDate]                                               NVARCHAR (MAX) NULL,
    [CvvNumber]                                                NVARCHAR (MAX) NULL,
    [BillingAddress]                                           NVARCHAR (MAX) NULL,
    [PleaseEnterYourBillingAddress]                            NVARCHAR (MAX) NULL,
    [Address1]                                                 NVARCHAR (MAX) NULL,
    [Address2]                                                 NVARCHAR (MAX) NULL,
    [City]                                                     NVARCHAR (MAX) NULL,
    [State]                                                    NVARCHAR (MAX) NULL,
    [PostCode]                                                 NVARCHAR (MAX) NULL,
    [MandatoryForCardsIssuedInUsa]                             NVARCHAR (MAX) NULL,
    [MandatoryForCardsIssuedOnCanadaOrUsa]                     NVARCHAR (MAX) NULL,
    [TheNamedVoucherHolderMustBeAtravellerOnThisBooking]       NVARCHAR (MAX) NULL,
    [EnterYourVoucherReferenceAndPin]                          NVARCHAR (MAX) NULL,
    [VoucherPayment]                                           NVARCHAR (MAX) NULL,
    [EnterThe6CharacterCodeForYourVoucher]                     NVARCHAR (MAX) NULL,
    [VoucherReference]                                         NVARCHAR (MAX) NULL,
    [VoucherPin]                                               NVARCHAR (MAX) NULL,
    [VerifyVoucher]                                            NVARCHAR (MAX) NULL,
    [TotalPaymentDue]                                          NVARCHAR (MAX) NULL,
    [PleaseSelect]                                             NVARCHAR (MAX) NULL,
    [SorryCardIsExpired]                                       NVARCHAR (MAX) NULL,
    [TheZipCodeIsMandatory]                                    NVARCHAR (MAX) NULL,
    [TheStateAndZipCodeAreMandatory]                           NVARCHAR (MAX) NULL,
    [InvalidCardNumber]                                        NVARCHAR (MAX) NULL,
    [PleaseWaitWhilstWeConfirmYourBooking]                     NVARCHAR (MAX) NULL,
    [ThisWillOnlyTakeAFewMoments]                              NVARCHAR (MAX) NULL,
    [PleaseWaitWhilstWeConnectToThePaymentGateway]             NVARCHAR (MAX) NULL,
    [PayLaterBenefitOne]                                       NVARCHAR (MAX) NULL,
    [PayLaterBenefitTwo]                                       NVARCHAR (MAX) NULL,
    [PayLaterBenefitThree]                                     NVARCHAR (MAX) NULL,
    [Hours]                                                    NVARCHAR (MAX) NULL,
    [CvvNumberTooltip]                                         NVARCHAR (MAX) NULL,
    [Hour]                                                     NVARCHAR (MAX) NULL,
    [Minute]                                                   NVARCHAR (MAX) NULL,
    [Minutes]                                                  NVARCHAR (MAX) NULL,
    [And]                                                      NVARCHAR (MAX) NULL,
    [CardVerification]                                         NVARCHAR (MAX) NULL,
    [Loading]                                                  NVARCHAR (MAX) NULL,
    [UnfortunatelyOneOrMoreSeatsIsNoLongerAvailable]           NVARCHAR (MAX) NULL,
    [YourFlightMustBePaidForNow]                               NVARCHAR (MAX) NULL,
    [MigsPaymentTimeout]                                       NVARCHAR (MAX) NULL,
    [RedirectionMessage]                                       NVARCHAR (MAX) NULL,
    [MigsTimeoutDescription]                                   NVARCHAR (MAX) NULL,
    [BillingCountryDropDownListSelectText]                     NVARCHAR (MAX) NULL,
    [CardTypeDropDownSelectText]                               NVARCHAR (MAX) NULL,
    [PayLaterInstructionsForPayingAtPaymentPointText]          NVARCHAR (MAX) NULL,
    [TheCanadianStateAreMandatory]                             NVARCHAR (MAX) NULL,
    [ScrollDownToAcceptTermsConditionsAndProceed]              NVARCHAR (MAX) NULL,
    [IfYouPayWithCreditCardFlyDubaiWillAskToSeeItNoSelected]   NVARCHAR (MAX) NULL,
    [InvalidCreditCardType]                                    NVARCHAR (MAX) NULL,
    [IfYouPayWithCreditCardFlyDubaiWillAskToSeeItNoSelectedTA] NVARCHAR (MAX) NULL,
    [IfYouPayWithCreditCardFlyDubaiWillAskToSeeItTA]           NVARCHAR (MAX) NULL,
    [PayNowTabConsumer]                                        NVARCHAR (MAX) NULL,
    [PayLaterTabConsumer]                                      NVARCHAR (MAX) NULL,
    [PayNowTabTA]                                              NVARCHAR (MAX) NULL,
    [PayLaterTabTA]                                            NVARCHAR (MAX) NULL,
    [PayNowTabMobile]                                          NVARCHAR (MAX) NULL,
    [PayLaterTabMobile]                                        NVARCHAR (MAX) NULL,
    [PCILogo]                                                  NVARCHAR (MAX) NULL,
    [OR]                                                       NVARCHAR (MAX) NULL,
    [PayLaterButtonText]                                       NVARCHAR (MAX) NULL,
    [TAToViewPaymentDetails]                                   NVARCHAR (MAX) NULL,
    [TAClickHere]                                              NVARCHAR (MAX) NULL,
    [TAPaymentDetails]                                         NVARCHAR (MAX) NULL,
    [TACostBreakdown]                                          NVARCHAR (MAX) NULL,
    [TAInvoice]                                                NVARCHAR (MAX) NULL,
    [TABalanceDue]                                             NVARCHAR (MAX) NULL,
    [TAVoucherReference]                                       NVARCHAR (MAX) NULL,
    [TACardNumber]                                             NVARCHAR (MAX) NULL,
    [TACreditCardWillBeChecked]                                NVARCHAR (MAX) NULL,
    [TAAirfare]                                                NVARCHAR (MAX) NULL,
    [TATax]                                                    NVARCHAR (MAX) NULL,
    [TAOptionalExtras]                                         NVARCHAR (MAX) NULL,
    [TATravelInsurance]                                        NVARCHAR (MAX) NULL,
    [TATransactionFee]                                         NVARCHAR (MAX) NULL,
    [TAPenaltyFee]                                             NVARCHAR (MAX) NULL,
    [TADebitCreditCardFee]                                     NVARCHAR (MAX) NULL,
    [TATotal]                                                  NVARCHAR (MAX) NULL,
    [TACash]                                                   NVARCHAR (MAX) NULL,
    [TAElectronicTicketNumber]                                 NVARCHAR (MAX) NULL,
    [TARefundedtotravelAgent]                                  NVARCHAR (MAX) NULL,
    [TARefundedThroughVoucherTo]                               NVARCHAR (MAX) NULL,
    [TARefundedToCreditCard]                                   NVARCHAR (MAX) NULL,
    [TAPayNowBenefitThree]                                     VARCHAR (MAX)  NULL,
    [TAPayLaterBenefitThree]                                   VARCHAR (MAX)  NULL,
    [TAPayNowBenefitOne]                                       VARCHAR (MAX)  NULL,
    [TAPayLaterBenefitOne]                                     VARCHAR (MAX)  NULL,
    [TAPayNowBenefitTwo]                                       VARCHAR (MAX)  NULL,
    [TAPayLaterBenefitTwo]                                     VARCHAR (MAX)  NULL,
    [CookiesDisabledTitle]                                     NVARCHAR (MAX) NULL,
    [CookiesDisabledMessage]                                   NVARCHAR (MAX) NULL,
    [CookiesDisabledGoToBankButton]                            NVARCHAR (MAX) NULL,
    [CookiesDisabledCancelButton]                              NVARCHAR (MAX) NULL,
    [PaymentPageRefreshAlert]                                  NVARCHAR (MAX) NULL,
    [PaymentPageFailureAlert]                                  NVARCHAR (MAX) NULL,
    [ToggleInterstitialLabel]                                  NVARCHAR (MAX) NULL,
    [ToggleInterstitialLoadingLabel]                           NVARCHAR (MAX) NULL,
    [CcInitialWarningMessage]                                  NVARCHAR (MAX) NULL,
    [CcReattemptWarningMessage]                                NVARCHAR (MAX) NULL,
    [ProcessingYourPayment]                                    NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);

















