CREATE TABLE [dbo].[PressGalleryLabels] (
    [PressGalleryLabelsId]  INT            IDENTITY (1, 1) NOT NULL,
    [ImagesTitle]           NVARCHAR (MAX) NULL,
    [VideosTitle]           NVARCHAR (MAX) NULL,
    [Sort]                  NVARCHAR (MAX) NULL,
    [SortBy]                NVARCHAR (MAX) NULL,
    [AllCategories]         NVARCHAR (MAX) NULL,
    [PagingText]            NVARCHAR (MAX) NULL,
    [PaginationNext]        NVARCHAR (MAX) NULL,
    [PaginationPrevious]    NVARCHAR (MAX) NULL,
    [DownloadOptions]       NVARCHAR (MAX) NULL,
    [DownloadLink]          NVARCHAR (MAX) NULL,
    [SmallImage]            NVARCHAR (MAX) NULL,
    [MediumImage]           NVARCHAR (MAX) NULL,
    [LargeImage]            NVARCHAR (MAX) NULL,
    [LowVideo]              NVARCHAR (MAX) NULL,
    [MediumVideo]           NVARCHAR (MAX) NULL,
    [HighVideo]             NVARCHAR (MAX) NULL,
    [EmailPrompt]           NVARCHAR (MAX) NULL,
    [SubmitEmail]           NVARCHAR (MAX) NULL,
    [SidebarTitle]          NVARCHAR (MAX) NULL,
    [SidebarSearchButton]   NVARCHAR (MAX) NULL,
    [LightboxCategoryLabel] NVARCHAR (MAX) NULL,
    [LightboxHeadingLabel]  NVARCHAR (MAX) NULL,
    [LanguageId]            INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([PressGalleryLabelsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

