CREATE TABLE [dbo].[ResultsTabLabels] (
    [Language]                   NVARCHAR (128) NOT NULL,
    [To]                         NVARCHAR (MAX) NULL,
    [On]                         NVARCHAR (MAX) NULL,
    [Outbound]                   NVARCHAR (MAX) NULL,
    [Return]                     NVARCHAR (MAX) NULL,
    [Journey]                    NVARCHAR (MAX) NULL,
    [BasedOn24HourClock]         NVARCHAR (MAX) NULL,
    [NextDay]                    NVARCHAR (MAX) NULL,
    [PreviousDay]                NVARCHAR (MAX) NULL,
    [Next3Days]                  NVARCHAR (MAX) NULL,
    [Previous3Days]              NVARCHAR (MAX) NULL,
    [Departure]                  NVARCHAR (MAX) NULL,
    [Arrival]                    NVARCHAR (MAX) NULL,
    [Duration]                   NVARCHAR (MAX) NULL,
    [Stop]                       NVARCHAR (MAX) NULL,
    [Stops]                      NVARCHAR (MAX) NULL,
    [FlightNumber]               NVARCHAR (MAX) NULL,
    [PricePerPassenger]          NVARCHAR (MAX) NULL,
    [SeatsLeft]                  NVARCHAR (MAX) NULL,
    [SoldOut]                    NVARCHAR (MAX) NULL,
    [PromoFare]                  NVARCHAR (MAX) NULL,
    [NoChange]                   NVARCHAR (MAX) NULL,
    [PayToChange]                NVARCHAR (MAX) NULL,
    [FreeToChange]               NVARCHAR (MAX) NULL,
    [Sunday]                     NVARCHAR (MAX) NULL,
    [Monday]                     NVARCHAR (MAX) NULL,
    [Tuesday]                    NVARCHAR (MAX) NULL,
    [Wednesday]                  NVARCHAR (MAX) NULL,
    [Thursday]                   NVARCHAR (MAX) NULL,
    [Friday]                     NVARCHAR (MAX) NULL,
    [Saturday]                   NVARCHAR (MAX) NULL,
    [NoFlights]                  NVARCHAR (MAX) NULL,
    [Cheapest]                   NVARCHAR (MAX) NULL,
    [NextMonth]                  NVARCHAR (MAX) NULL,
    [PreviousMonth]              NVARCHAR (MAX) NULL,
    [NoChangeTooltip]            NVARCHAR (MAX) NULL,
    [PayToChangeTooltip]         NVARCHAR (MAX) NULL,
    [FreeToChangeTooltip]        NVARCHAR (MAX) NULL,
    [OneOrMoreStopsTooltip]      NVARCHAR (MAX) NULL,
    [Depart]                     NVARCHAR (MAX) NULL,
    [Arrive]                     NVARCHAR (MAX) NULL,
    [BasicFare]                  NVARCHAR (MAX) NULL,
    [Economy]                    NVARCHAR (MAX) NULL,
    [Business]                   NVARCHAR (MAX) NULL,
    [NotAvailable]               NVARCHAR (MAX) NULL,
    [NOBusinessInventory]        NVARCHAR (MAX) NULL,
    [AlternativeAirportsMessage] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);







