CREATE TABLE [dbo].[ResultsLabels] (
    [Language]                            NVARCHAR (128) NOT NULL,
    [ViewingOptions]                      NVARCHAR (MAX) NULL,
    [Currency]                            NVARCHAR (MAX) NULL,
    [ChangeCurrency]                      NVARCHAR (MAX) NULL,
    [FareType]                            NVARCHAR (MAX) NULL,
    [Go]                                  NVARCHAR (MAX) NULL,
    [OneDayView]                          NVARCHAR (MAX) NULL,
    [ThreeDayView]                        NVARCHAR (MAX) NULL,
    [MonthView]                           NVARCHAR (MAX) NULL,
    [To]                                  NVARCHAR (MAX) NULL,
    [On]                                  NVARCHAR (MAX) NULL,
    [Passengers]                          NVARCHAR (MAX) NULL,
    [Adults]                              NVARCHAR (MAX) NULL,
    [Children]                            NVARCHAR (MAX) NULL,
    [Infants]                             NVARCHAR (MAX) NULL,
    [SearchAgain]                         NVARCHAR (MAX) NULL,
    [Journey]                             NVARCHAR (MAX) NULL,
    [LowestFaresAvailable]                NVARCHAR (MAX) NULL,
    [NoChangeFaresOnly]                   NVARCHAR (MAX) NULL,
    [PayToChangeFaresOnly]                NVARCHAR (MAX) NULL,
    [FreeToChangeFaresOnly]               NVARCHAR (MAX) NULL,
    [PromoFaresOnly]                      NVARCHAR (MAX) NULL,
    [IAmFlyingFrom]                       NVARCHAR (MAX) NULL,
    [TwelvePlus]                          NVARCHAR (MAX) NULL,
    [TwoTo12]                             NVARCHAR (MAX) NULL,
    [Under2]                              NVARCHAR (MAX) NULL,
    [Under2Tooltip]                       NVARCHAR (MAX) NULL,
    [ShowFlights]                         NVARCHAR (MAX) NULL,
    [SorryThereWasAProblemWithYourSearch] NVARCHAR (MAX) NULL,
    [PleaseCheckAndTryAgain]              NVARCHAR (MAX) NULL,
    [InfantPassengers]                    NVARCHAR (MAX) NULL,
    [Arriving]                            NVARCHAR (MAX) NULL,
    [Stop]                                NVARCHAR (MAX) NULL,
    [SeatsLeft]                           NVARCHAR (MAX) NULL,
    [PerPerson]                           NVARCHAR (MAX) NULL,
    [Departing]                           NVARCHAR (MAX) NULL,
    [MoreInfo]                            NVARCHAR (MAX) NULL,
    [LoadingResults]                      NVARCHAR (MAX) NULL,
    [PleaseWait]                          NVARCHAR (MAX) NULL,
    [Loading]                             NVARCHAR (MAX) NULL,
    [Sort]                                NVARCHAR (MAX) NULL,
    [Prev]                                NVARCHAR (MAX) NULL,
    [Next]                                NVARCHAR (MAX) NULL,
    [PleaseSelectAFlightFromTheList]      NVARCHAR (MAX) NULL,
    [AddedToBooking]                      NVARCHAR (MAX) NULL,
    [Added]                               NVARCHAR (MAX) NULL,
    [LessInfo]                            NVARCHAR (MAX) NULL,
    [LoadingImageUrl]                     NVARCHAR (MAX) NULL,
    [MultipleAirportsMessage]             NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);





