CREATE TABLE [dbo].[RouteMessageVersions] (
    [RouteMessageVersionId]            INT            IDENTITY (1, 1) NOT NULL,
    [Title]                            NVARCHAR (MAX) NOT NULL,
    [OriginAirportCode]                NVARCHAR (MAX) NULL,
    [DestinationAirportCode]           NVARCHAR (MAX) NULL,
    [Message]                          NVARCHAR (MAX) NOT NULL,
    [OnMonday]                         BIT            NULL,
    [OnTuesday]                        BIT            NULL,
    [OnWednesday]                      BIT            NULL,
    [OnThursday]                       BIT            NULL,
    [OnFriday]                         BIT            NULL,
    [OnSaturday]                       BIT            NULL,
    [OnSunday]                         BIT            NULL,
    [ParentId]                         INT            NOT NULL,
    [UrlIdentifier]                    NVARCHAR (MAX) NULL,
    [CmsName]                          NVARCHAR (MAX) NULL,
    [Version]                          INT            NOT NULL,
    [IsDraft]                          BIT            NOT NULL,
    [CreatedById]                      INT            NULL,
    [CreatedDate]                      DATETIME2 (7)  NULL,
    [ApprovedById]                     INT            NULL,
    [ApprovedDate]                     DATETIME2 (7)  NULL,
    [PublishedById]                    INT            NULL,
    [PublishedDate]                    DATETIME2 (7)  NULL,
    [UnpublishedById]                  INT            NULL,
    [UnpublishedDate]                  DATETIME2 (7)  NULL,
    [PublishPeriodStartDate]           DATETIME2 (7)  NOT NULL,
    [PublishPeriodEndDate]             DATETIME2 (7)  NOT NULL,
    [RouteDateRangeFrom]               DATETIME2 (7)  NULL,
    [RouteDateRangeTo]                 DATETIME2 (7)  NULL,
    [AffectedDates]                    NVARCHAR (MAX) NULL,
    [FlightNumberStartRange]           INT            NULL,
    [FlightNumberEndRange]             INT            NULL,
    [AffectedFlightNumbers]            NVARCHAR (MAX) NULL,
    [CountryOriginId]                  INT            NULL,
    [CountryDestinationId]             INT            NULL,
    [IsAirportPreferredForOrigin]      BIT            DEFAULT ((1)) NOT NULL,
    [IsAirportPreferredForDestination] BIT            DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([RouteMessageVersionId] ASC),
    CONSTRAINT [RouteMessageVersion_ApprovedBy] FOREIGN KEY ([ApprovedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [RouteMessageVersion_CreatedBy] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [RouteMessageVersion_Parent] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[RouteMessages] ([RouteMessageId]),
    CONSTRAINT [RouteMessageVersion_PublishedBy] FOREIGN KEY ([PublishedById]) REFERENCES [dbo].[Members] ([Id]),
    CONSTRAINT [RouteMessageVersion_UnpublishedBy] FOREIGN KEY ([UnpublishedById]) REFERENCES [dbo].[Members] ([Id])
);






