CREATE TABLE [dbo].[ShowAmendmentsLabels] (
    [Language]                              NVARCHAR (128) NOT NULL,
    [ApplyAmendmentsAccessibilityTitleText] NVARCHAR (MAX) NULL,
    [BookingReferenceLabelText]             NVARCHAR (MAX) NULL,
    [ChangesAreHighlightedBelowText]        NVARCHAR (MAX) NULL,
    [FareLabelText]                         NVARCHAR (MAX) NULL,
    [TaxesLabelText]                        NVARCHAR (MAX) NULL,
    [ServicesSectionLabelText]              NVARCHAR (MAX) NULL,
    [BaggageLabelText]                      NVARCHAR (MAX) NULL,
    [SeatingTotalLabelText]                 NVARCHAR (MAX) NULL,
    [NonRefundableLabelText]                NVARCHAR (MAX) NULL,
    [InsuranceLabelText]                    NVARCHAR (MAX) NULL,
    [PenaltyLabelText]                      NVARCHAR (MAX) NULL,
    [TotalLabelText]                        NVARCHAR (MAX) NULL,
    [ExcludingCreditDebitFeeLabelText]      NVARCHAR (MAX) NULL,
    [AdditionalPaymentLabelText]            NVARCHAR (MAX) NULL,
    [TotalRefundLabelText]                  NVARCHAR (MAX) NULL,
    [ApplyAmendmentsButton]                 NVARCHAR (MAX) NULL,
    [CancelAmendmentsButton]                NVARCHAR (MAX) NULL,
    [JourneyOriginDestinationHeadingText]   NVARCHAR (MAX) NULL,
    [DepartureDateLabelText]                NVARCHAR (MAX) NULL,
    [PreviousFlightLabelText]               NVARCHAR (MAX) NULL,
    [FlightChangedToLabelText]              NVARCHAR (MAX) NULL,
    [FlightNumberColumnHeading]             NVARCHAR (MAX) NULL,
    [DepartingColumnHeading]                NVARCHAR (MAX) NULL,
    [ArrivalColumnHeading]                  NVARCHAR (MAX) NULL,
    [DurationColumnHeading]                 NVARCHAR (MAX) NULL,
    [PassengersColumnHeading]               NVARCHAR (MAX) NULL,
    [FareTypeColumnHeading]                 NVARCHAR (MAX) NULL,
    [BaggageColumnHeading]                  NVARCHAR (MAX) NULL,
    [SeatColumnHeading]                     NVARCHAR (MAX) NULL,
    [ExtraColumnHeading]                    NVARCHAR (MAX) NULL,
    [TaxesColumnHeading]                    NVARCHAR (MAX) NULL,
    [SubTotalColumnHeading]                 NVARCHAR (MAX) NULL,
    [KgHandBaggageSuffix]                   NVARCHAR (MAX) NULL,
    [KgCheckedBaggageSuffix]                NVARCHAR (MAX) NULL,
    [InsuranceRefLabelText]                 NVARCHAR (MAX) NULL,
    [BasedOn24HourClockText]                NVARCHAR (MAX) NULL,
    [JourneyTotalLabelText]                 NVARCHAR (MAX) NULL,
    [InclusiveOfTaxesText]                  NVARCHAR (MAX) NULL,
    [InFlightEntertainmentLabelText]        NVARCHAR (MAX) NULL,
    [OptionalExtras]                        NVARCHAR (MAX) NULL,
    [Meals]                                 NVARCHAR (MAX) NULL,
    [Insurance]                             NVARCHAR (MAX) NULL,
    [CabinClass]                            NVARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);





