CREATE TABLE [dbo].[SignUpLabels] (
    [SignUpLabelsId]                         INT            IDENTITY (1, 1) NOT NULL,
    [ConfrimationHeader]                     NVARCHAR (MAX) NULL,
    [DefaultHeader]                          NVARCHAR (MAX) NULL,
    [YourDetailsHeader]                      NVARCHAR (MAX) NULL,
    [ContactTitle]                           NVARCHAR (MAX) NULL,
    [AllowedContactTitles]                   NVARCHAR (MAX) NULL,
    [DefaultTitleOption]                     NVARCHAR (MAX) NULL,
    [ContactFirstName]                       NVARCHAR (MAX) NULL,
    [ContactLastName]                        NVARCHAR (MAX) NULL,
    [ContactEmail]                           NVARCHAR (MAX) NULL,
    [ContactCountry]                         NVARCHAR (MAX) NULL,
    [YouPreferencesHeader]                   NVARCHAR (MAX) NULL,
    [PreferencesIntroductionText]            NVARCHAR (MAX) NULL,
    [PreferredLanguageLabel]                 NVARCHAR (MAX) NULL,
    [PreferredLanguageEnglish]               NVARCHAR (MAX) NULL,
    [PreferredLanguageArabic]                NVARCHAR (MAX) NULL,
    [ReceiveOffersFromAllDestinations]       NVARCHAR (MAX) NULL,
    [ReceiveOffersFromFollowingDestinations] NVARCHAR (MAX) NULL,
    [PickDestinationInstructions]            NVARCHAR (MAX) NULL,
    [DefaultDestinationOption]               NVARCHAR (MAX) NULL,
    [SignUpToSpecialOffers]                  NVARCHAR (MAX) NULL,
    [SignUpToSpecialOffersSummary]           NVARCHAR (MAX) NULL,
    [SignUpToMonthlyNews]                    NVARCHAR (MAX) NULL,
    [SignUpToMonthlyNewsSummary]             NVARCHAR (MAX) NULL,
    [SignUpToPartnerPromotions]              NVARCHAR (MAX) NULL,
    [SignUpToPartnerPromotionsSummary]       NVARCHAR (MAX) NULL,
    [SkipButton]                             NVARCHAR (MAX) NULL,
    [SubmitButton]                           NVARCHAR (MAX) NULL,
    [SmallModuleSummaryText]                 NVARCHAR (MAX) NULL,
    [EmailExample]                           NVARCHAR (MAX) NULL,
    [NewsletterSignupButton]                 NVARCHAR (MAX) NULL,
    [NewsletterSignupHeader]                 NVARCHAR (MAX) NULL,
    [LanguageId]                             INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([SignUpLabelsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

