CREATE TABLE [dbo].[SpecialOfferLabels] (
    [SpecialOfferLabelsId]        INT            IDENTITY (1, 1) NOT NULL,
    [ModuleTitle]                 NVARCHAR (MAX) NULL,
    [SeeAllLink]                  NVARCHAR (MAX) NULL,
    [PromoCode]                   NVARCHAR (MAX) NULL,
    [BookButtonText]              NVARCHAR (MAX) NULL,
    [UseThisCodeButtonText]       NVARCHAR (MAX) NULL,
    [TermsAndConditionsLink]      NVARCHAR (MAX) NULL,
    [TermsAndConditionsHeading]   NVARCHAR (MAX) NULL,
    [Free]                        NVARCHAR (MAX) NULL,
    [SearchTitle]                 NVARCHAR (MAX) NULL,
    [SearchFlyingFrom]            NVARCHAR (MAX) NULL,
    [SearchFlyingFromSelect]      NVARCHAR (MAX) NULL,
    [SearchSortBy]                NVARCHAR (MAX) NULL,
    [SearchAndSortBy]             NVARCHAR (MAX) NULL,
    [SearchGo]                    NVARCHAR (MAX) NULL,
    [SearchPaging]                NVARCHAR (MAX) NULL,
    [SearchPagingPrevious]        NVARCHAR (MAX) NULL,
    [SearchPagingNext]            NVARCHAR (MAX) NULL,
    [SearchSortTime]              NVARCHAR (MAX) NULL,
    [SearchSortPrice]             NVARCHAR (MAX) NULL,
    [SearchSortHotels]            NVARCHAR (MAX) NULL,
    [SearchSortCarHire]           NVARCHAR (MAX) NULL,
    [SearchSortEndingSoonest]     NVARCHAR (MAX) NULL,
    [SearchSortNewlyListed]       NVARCHAR (MAX) NULL,
    [SearchSortLowestFirst]       NVARCHAR (MAX) NULL,
    [SearchSortHighestFirst]      NVARCHAR (MAX) NULL,
    [SearchSortPriceLowestFirst]  NVARCHAR (MAX) NULL,
    [SearchSortPriceHighestFirst] NVARCHAR (MAX) NULL,
    [TooltipHeading]              NVARCHAR (MAX) NULL,
    [TooltipText]                 NVARCHAR (MAX) NULL,
    [LanguageId]                  INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([SpecialOfferLabelsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

