CREATE TABLE [dbo].[SpecialOfferVersions] (
    [SpecialOfferVersionId]                   INT             IDENTITY (1, 1) NOT NULL,
    [AvailableToNonRegisteredUsers]           BIT             NULL,
    [AvailableToRegisteredUsers]              BIT             NULL,
    [AvailableToStaff]                        BIT             NULL,
    [AvailableToTravelAgents]                 BIT             NULL,
    [SpecialOfferType]                        NVARCHAR (MAX)  NULL,
    [Title]                                   NVARCHAR (MAX)  NULL,
    [Image]                                   INT             NULL,
    [ImagePath]                               NVARCHAR (MAX)  NULL,
    [PromotionalCode]                         NVARCHAR (MAX)  NULL,
    [DisplayPromotionalCode]                  BIT             NOT NULL,
    [AdditionalInformation]                   NVARCHAR (MAX)  NULL,
    [Price]                                   DECIMAL (18, 2) NOT NULL,
    [IsPercentage]                            BIT             NOT NULL,
    [PriceSuffix]                             NVARCHAR (MAX)  NULL,
    [TravellingFrom]                          NVARCHAR (MAX)  NULL,
    [TravellingTo]                            NVARCHAR (MAX)  NULL,
    [ThirdPartyUrl]                           NVARCHAR (MAX)  NULL,
    [BookButtonUrl]                           NVARCHAR (MAX)  NULL,
    [TermsAndConditionsHtml]                  NVARCHAR (MAX)  NULL,
    [IsHotel]                                 BIT             NOT NULL,
    [IsCarHire]                               BIT             NOT NULL,
    [IsGlobal]                                BIT             NOT NULL,
    [ExpiryDate]                              DATETIME2 (7)   NULL,
    [ParentId]                                INT             NOT NULL,
    [UrlIdentifier]                           NVARCHAR (MAX)  NULL,
    [CmsName]                                 NVARCHAR (MAX)  NULL,
    [Version]                                 INT             NOT NULL,
    [IsDraft]                                 BIT             NOT NULL,
    [CreatedById]                             INT             NULL,
    [CreatedDate]                             DATETIME2 (7)   NULL,
    [ApprovedById]                            INT             NULL,
    [ApprovedDate]                            DATETIME2 (7)   NULL,
    [PublishedById]                           INT             NULL,
    [PublishedDate]                           DATETIME2 (7)   NULL,
    [UnpublishedById]                         INT             NULL,
    [UnpublishedDate]                         DATETIME2 (7)   NULL,
    [AirportInformation_AirportInformationId] INT             NULL,
    [Currency]                                NVARCHAR (100)  NULL,
    PRIMARY KEY CLUSTERED ([SpecialOfferVersionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

