CREATE TABLE [dbo].[TAViewBalanceReportLabels] (
    [Language]              NVARCHAR (128) NOT NULL,
    [ReportTitle]           NVARCHAR (MAX) NULL,
    [TransactionDates]      NVARCHAR (MAX) NULL,
    [InvoiceNo]             NVARCHAR (MAX) NULL,
    [PaymentDate]           NVARCHAR (MAX) NULL,
    [PNR]                   NVARCHAR (MAX) NULL,
    [IATAnumber]            NVARCHAR (MAX) NULL,
    [PayerID]               NVARCHAR (MAX) NULL,
    [Currency]              NVARCHAR (MAX) NULL,
    [Amount]                NVARCHAR (MAX) NULL,
    [DepositDate]           NVARCHAR (MAX) NULL,
    [DepositAmount]         NVARCHAR (MAX) NULL,
    [BalanceDue]            NVARCHAR (MAX) NULL,
    [PaymentRef]            NVARCHAR (MAX) NULL,
    [CumulativeTitle]       NVARCHAR (MAX) NULL,
    [CumulativeTotalsTitle] NVARCHAR (MAX) NULL,
    [summaryTitle]          NVARCHAR (MAX) NULL,
    [TotalCharges]          NVARCHAR (MAX) NULL,
    [TotalPayments]         NVARCHAR (MAX) NULL,
    [OverallBalance]        NVARCHAR (MAX) NULL,
    [UserID]                NVARCHAR (MAX) NULL,
    [TotalPassengers]       NVARCHAR (MAX) NULL,
    [TotalSegments]         NVARCHAR (MAX) NULL,
    [PaxName]               NVARCHAR (MAX) NULL,
    [DeapartureDate]        NVARCHAR (MAX) NULL,
    [Comments]              NVARCHAR (MAX) NULL,
    [BookingDate]           NVARCHAR (MAX) NULL,
    [BookedCurrency]        NVARCHAR (MAX) NULL,
    [BookedAmount]          NVARCHAR (MAX) NULL,
    [InformationTitle]      NVARCHAR (MAX) NULL,
    [CloseTitle]            NVARCHAR (MAX) NULL,
    [NoReportsMessage]      NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_ViewBalanceReportLabels] PRIMARY KEY CLUSTERED ([Language] ASC)
);

