CREATE TABLE [dbo].[UniquePageTitles] (
    [Language]                           NVARCHAR (10)  NOT NULL,
    [FlightSearchResultOneDayView]       NVARCHAR (MAX) NULL,
    [FlightSearchResultThreeDayView]     NVARCHAR (MAX) NULL,
    [FlightSearchResultMonthView]        NVARCHAR (MAX) NULL,
    [OPtionalExtraPage]                  NVARCHAR (MAX) NULL,
    [PassngerInformationPage]            NVARCHAR (MAX) NULL,
    [PaymentPage]                        NVARCHAR (MAX) NULL,
    [ConfirmaionPage]                    NVARCHAR (MAX) NULL,
    [AccountForgottenPassword]           NVARCHAR (MAX) NULL,
    [AccountLogin]                       NVARCHAR (MAX) NULL,
    [AccountLogOut]                      NVARCHAR (MAX) NULL,
    [ContactUsResults]                   NVARCHAR (MAX) NULL,
    [ContactUsSearch]                    NVARCHAR (MAX) NULL,
    [ResultsForChangeLogicalFlightDates] NVARCHAR (MAX) NULL,
    [UpgradeToBusiness]                  NVARCHAR (MAX) NULL,
    [ErrorFileNotFound]                  NVARCHAR (MAX) NULL,
    [AdditionalPassengerDetails]         NVARCHAR (MAX) NULL,
    [AdditionalPassengerOptionalExtras]  NVARCHAR (MAX) NULL,
    [ShowAmendments]                     NVARCHAR (MAX) NULL,
    [MobileFind]                         NVARCHAR (MAX) NULL,
    [MobileList]                         NVARCHAR (MAX) NULL,
    [MobileViewTicket]                   NVARCHAR (MAX) NULL,
    [MobileSearchSearch]                 NVARCHAR (MAX) NULL,
    [MobileResults]                      NVARCHAR (MAX) NULL,
    [MobileStatusSearch]                 NVARCHAR (MAX) NULL,
    [MobileIndex]                        NVARCHAR (MAX) NULL,
    [MobileSessionTimeout]               NVARCHAR (MAX) NULL,
    [MobileTimetableResults]             NVARCHAR (MAX) NULL,
    [MobileTimetableSearch]              NVARCHAR (MAX) NULL,
    [TASignin]                           NVARCHAR (MAX) NULL
);

