CREATE TABLE [dbo].[YourJourneyLabels] (
    [Language]                                            NVARCHAR (128) NOT NULL,
    [YourJourney]                                         NVARCHAR (MAX) NULL,
    [To]                                                  NVARCHAR (MAX) NULL,
    [Departs]                                             NVARCHAR (MAX) NULL,
    [Arrives]                                             NVARCHAR (MAX) NULL,
    [Day]                                                 NVARCHAR (MAX) NULL,
    [Days]                                                NVARCHAR (MAX) NULL,
    [Duration]                                            NVARCHAR (MAX) NULL,
    [PayToChangeFare]                                     NVARCHAR (MAX) NULL,
    [FreeToChangeFare]                                    NVARCHAR (MAX) NULL,
    [NoChangeFare]                                        NVARCHAR (MAX) NULL,
    [Adult]                                               NVARCHAR (MAX) NULL,
    [Child]                                               NVARCHAR (MAX) NULL,
    [Infant]                                              NVARCHAR (MAX) NULL,
    [Adults]                                              NVARCHAR (MAX) NULL,
    [Children]                                            NVARCHAR (MAX) NULL,
    [Infants]                                             NVARCHAR (MAX) NULL,
    [Continue]                                            NVARCHAR (MAX) NULL,
    [Hr]                                                  NVARCHAR (MAX) NULL,
    [Hrs]                                                 NVARCHAR (MAX) NULL,
    [Min]                                                 NVARCHAR (MAX) NULL,
    [Mins]                                                NVARCHAR (MAX) NULL,
    [Kg]                                                  NVARCHAR (MAX) NULL,
    [HandBaggage]                                         NVARCHAR (MAX) NULL,
    [CheckedBaggage]                                      NVARCHAR (MAX) NULL,
    [Free]                                                NVARCHAR (MAX) NULL,
    [Added]                                               NVARCHAR (MAX) NULL,
    [TaxesAndCharges]                                     NVARCHAR (MAX) NULL,
    [Sector]                                              NVARCHAR (MAX) NULL,
    [ViewFullBreakdown]                                   NVARCHAR (MAX) NULL,
    [Discounts]                                           NVARCHAR (MAX) NULL,
    [PromoCode]                                           NVARCHAR (MAX) NULL,
    [Total]                                               NVARCHAR (MAX) NULL,
    [Under2Years]                                         NVARCHAR (MAX) NULL,
    [InclusiveOfAllTaxes]                                 NVARCHAR (MAX) NULL,
    [Included]                                            NVARCHAR (MAX) NULL,
    [Wheelchair]                                          NVARCHAR (MAX) NULL,
    [SeatAssignment]                                      NVARCHAR (MAX) NULL,
    [Stops]                                               NVARCHAR (MAX) NULL,
    [Insurance]                                           NVARCHAR (MAX) NULL,
    [SelectFLightToContimue]                              NVARCHAR (MAX) NULL,
    [Passengers]                                          NVARCHAR (MAX) NULL,
    [EditPassengerNames]                                  NVARCHAR (MAX) NULL,
    [Seats]                                               NVARCHAR (MAX) NULL,
    [AllPassengersOnAllYourJourneysAreCovered]            NVARCHAR (MAX) NULL,
    [Wheelchairs]                                         NVARCHAR (MAX) NULL,
    [Fees]                                                NVARCHAR (MAX) NULL,
    [CreditDebitCard]                                     NVARCHAR (MAX) NULL,
    [ViewSummary]                                         NVARCHAR (MAX) NULL,
    [ArrivalNextDayTooltip]                               NVARCHAR (MAX) NULL,
    [PayToChangeFareTooltip]                              NVARCHAR (MAX) NULL,
    [FreeToChangeFareTooltip]                             NVARCHAR (MAX) NULL,
    [NoChangeFareTooltip]                                 NVARCHAR (MAX) NULL,
    [ArrivalNextDay]                                      NVARCHAR (MAX) NULL,
    [WaitingTime]                                         NVARCHAR (MAX) NULL,
    [WhatsIncluded]                                       NVARCHAR (MAX) NULL,
    [HandBaggageAllowanceNotBiggerThan56X45X25Cm]         NVARCHAR (MAX) NULL,
    [CheckedBaggageAllowanceNotBiggerThan78X55X35Cm]      NVARCHAR (MAX) NULL,
    [ChangeOfDatesAllowedAdditionalFee]                   NVARCHAR (MAX) NULL,
    [AbilityToGetARefundVoucherWillBeIssued]              NVARCHAR (MAX) NULL,
    [NoRefundCancellationFee100Percent]                   NVARCHAR (MAX) NULL,
    [WhyNotUpgradeForUltimateFlexibility]                 NVARCHAR (MAX) NULL,
    [FlightNo]                                            NVARCHAR (MAX) NULL,
    [Departing]                                           NVARCHAR (MAX) NULL,
    [Arrival]                                             NVARCHAR (MAX) NULL,
    [CurrentFare]                                         NVARCHAR (MAX) NULL,
    [UpgradeYourFareType]                                 NVARCHAR (MAX) NULL,
    [NoUpgradesAvailable]                                 NVARCHAR (MAX) NULL,
    [AdditionalBenefitsForFlexibleTickets]                NVARCHAR (MAX) NULL,
    [IHaveReadAndAcceptFlydubais]                         NVARCHAR (MAX) NULL,
    [TermsAndConditions]                                  NVARCHAR (MAX) NULL,
    [Extra]                                               NVARCHAR (MAX) NULL,
    [UpgradeOptions]                                      NVARCHAR (MAX) NULL,
    [LocalTime]                                           NVARCHAR (MAX) NULL,
    [NoUpgradeRequired]                                   NVARCHAR (MAX) NULL,
    [ScrollToReviewYourSummaryAndContinueWithYourBooking] NVARCHAR (MAX) NULL,
    [TermsAndConditionsLinkUrl]                           NVARCHAR (MAX) CONSTRAINT [DF_YourJourneyLabels_TermsAndConditionsLinkUrl] DEFAULT ('#') NOT NULL,
    [TermsAndConditionsLink]                              NVARCHAR (MAX) NULL,
    [InFlightEntertainment]                               NVARCHAR (MAX) NULL,
    [PurchasedInFlightEntertainment]                      NVARCHAR (MAX) NULL,
    [BusinessFare]                                        NVARCHAR (MAX) NULL,
    [Cabin]                                               NVARCHAR (MAX) NULL,
    [BasicFare]                                           NVARCHAR (MAX) NULL,
    [Economy]                                             NVARCHAR (MAX) NULL,
    [Business]                                            NVARCHAR (MAX) NULL,
    [HotMealAndDrinks]                                    NVARCHAR (MAX) NULL,
    [BusinessMealTooltip]                                 NVARCHAR (MAX) NULL,
    [MealsIncluded]                                       NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);







