ALTER TABLE [dbo].[InterceptLightBoxes]
    ADD CONSTRAINT [PK_InterceptLightBox] PRIMARY KEY CLUSTERED ([Language] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

