// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using flydubai.Booking.Api.Booking.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace flydubai.Booking.Api.Booking
{
    [RoutePrefix("api/booking/email/{emailAddress}")]
    public partial class ApiBookingEmailEmailAddressController : ApiController
    {


        		/// <param name="emailAddress">email address for sharing the booking details</param>
		/// <returns>ApiBookingEmailEmailAddressGetOKResponseContent</returns>
        [ResponseType(typeof(ApiBookingEmailEmailAddressGetOKResponseContent))]
        [HttpGet]
        [Route("")]
        public virtual async Task<IHttpActionResult> GetBase([FromUri] string emailAddress)
        {
            // Do not modify this code
            return await ((IApiBookingEmailEmailAddressController)this).Get(emailAddress);
        }
    }
}
