// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using flydubai.Booking.Api.Booking.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace flydubai.Booking.Api.Booking
{
    [RoutePrefix("api/booking/retrieve/{pnr}/{lastName}")]
    public partial class ApiBookingRetrievePnrLastNameController : ApiController
    {


        		/// <param name="pnr">PNR for the booking</param>
		/// <param name="lastName">last name of any of the passenger in the booking</param>
		/// <returns>ApiBookingRetrievePnrLastNameGetOKResponseContent</returns>
        [ResponseType(typeof(ApiBookingRetrievePnrLastNameGetOKResponseContent))]
        [HttpGet]
        [Route("")]
        public virtual async Task<IHttpActionResult> GetBase([FromUri] string pnr,[FromUri] string lastName)
        {
            // Do not modify this code
            return await ((IApiBookingRetrievePnrLastNameController)this).Get(pnr,lastName);
        }
    }
}
