// Template: Models (ApiEnum.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace flydubai.Booking.Api.FlightSearch.Models
{
    public enum Level
    {
		Flight, Route, Passenger    
    }

}
