// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using flydubai.Booking.Api.Booking.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace flydubai.Booking.Api.Booking
{
    [RoutePrefix("api/booking/print")]
    public partial class ApiBookingPrintController : ApiController
    {


        		/// <returns>ApiBookingPrintGetOKResponseContent</returns>
        [ResponseType(typeof(ApiBookingPrintGetOKResponseContent))]
        [HttpGet]
        [Route("")]
        public virtual async Task<IHttpActionResult> GetBase()
        {
            // Do not modify this code
            return await ((IApiBookingPrintController)this).Get();
        }
    }
}
