// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace flydubai.Booking.Api.Booking.Models
{
    public partial class ApiBookingRetrievePnrLastNameGetOKResponseContent
    {
        


		[JsonProperty("passengerList")]
        public IList<PassengerList> PassengerList { get; set; }


		[JsonProperty("preferences")]
        public HttpFlydubaicomItinaryPreferences Preferences { get; set; }
    } // end class

} // end Models namespace

