/*
Deployment script for Prod_flydubai_aer

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "flydubai_aer"
:setvar DefaultFilePrefix "flydubai_aer"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping <unnamed>...';


GO
EXECUTE sp_droprolemember @rolename = N'db_datareader', @membername = N'TERMINAL\jdominguez';


GO
PRINT N'Dropping <unnamed>...';


GO
EXECUTE sp_droprolemember @rolename = N'db_datareader', @membername = N'TERMINAL\svaid';


GO
PRINT N'Dropping <unnamed>...';


GO
EXECUTE sp_droprolemember @rolename = N'db_owner', @membername = N'WEB2_LIVE_FZ';


GO
PRINT N'Dropping <unnamed>...';


GO
EXECUTE sp_droprolemember @rolename = N'db_owner', @membername = N'terminal\JHowland';


GO
PRINT N'Altering [cms]...';


GO
ALTER AUTHORIZATION
    ON SCHEMA::[cms]
    TO [dbo];


GO
PRINT N'Altering [dbo].[BookingLabels]...';


GO
ALTER TABLE [dbo].[BookingLabels]
    ADD [HotMeal]                   NVARCHAR (MAX) NULL,
        [NoMealOptionsInfent]       NVARCHAR (MAX) NULL,
        [Economy]                   NVARCHAR (MAX) NULL,
        [Business]                  NVARCHAR (MAX) NULL,
        [Basic]                     NVARCHAR (MAX) NULL,
        [BusinessHandBaggage]       NVARCHAR (MAX) NULL,
        [Premium]                   NVARCHAR (MAX) NULL,
        [BuySnacksAndDrinksOnBoard] NVARCHAR (MAX) NULL,
        [Meal]                      NVARCHAR (MAX) NULL;


GO
PRINT N'Altering [dbo].[FareTypeLabels]...';


GO
ALTER TABLE [dbo].[FareTypeLabels]
    ADD [FareType4Name]    NVARCHAR (MAX) NULL,
        [FareType4FeeText] NVARCHAR (MAX) NULL;


GO
PRINT N'Altering [dbo].[FareTypes]...';


GO
ALTER TABLE [dbo].[FareTypes]
    ADD [Fare4Image]       INT            NULL,
        [Fare4ImageUrl]    NVARCHAR (MAX) NULL,
        [Fare4Description] NVARCHAR (MAX) NULL;


GO
PRINT N'Altering [dbo].[OptionalExtrasLabels]...';


GO
ALTER TABLE [dbo].[OptionalExtrasLabels]
    ADD [Meal]                          NVARCHAR (MAX) NULL,
        [MealDefault]                   NVARCHAR (MAX) NULL,
        [NoDietary]                     NVARCHAR (MAX) NULL,
        [VegetarianMeal]                NVARCHAR (MAX) NULL,
        [MealDescription]               NVARCHAR (MAX) NULL,
        [InfantsNotHaveMeal]            NVARCHAR (MAX) NULL,
        [Economy]                       NVARCHAR (MAX) NULL,
        [Business]                      NVARCHAR (MAX) NULL,
        [IFEBusinessMessage]            NVARCHAR (MAX) NULL,
        [BuyMealOnBoard]                NVARCHAR (MAX) NULL,
        [DietaryRequirement]            NVARCHAR (MAX) NULL,
        [BusinessBaggageHeadding]       NVARCHAR (MAX) NULL,
        [BusinessBaggageDescription]    NVARCHAR (MAX) NULL,
        [BusinessIfeHeadding]           NVARCHAR (MAX) NULL,
        [BusinessIfeDescription]        NVARCHAR (MAX) NULL,
        [MixedBaggageHeadding]          NVARCHAR (MAX) NULL,
        [MixedBaggageDescription]       NVARCHAR (MAX) NULL,
        [MixedIfeHeadding]              NVARCHAR (MAX) NULL,
        [MixedIfeDescription]           NVARCHAR (MAX) NULL,
        [WhereToSitDescriptionBusiness] NVARCHAR (MAX) NULL,
        [WhereToSitDescriptionMixed]    NVARCHAR (MAX) NULL,
        [MealHeading]                   NVARCHAR (MAX) NULL,
        [InfantsNotHaveTASSRAssigned]   NVARCHAR (MAX) NULL;


GO
PRINT N'Altering [dbo].[ResultsTabLabels]...';


GO
ALTER TABLE [dbo].[ResultsTabLabels]
    ADD [Depart]       NVARCHAR (MAX) NULL,
        [Arrive]       NVARCHAR (MAX) NULL,
        [BasicFare]    NVARCHAR (MAX) NULL,
        [Economy]      NVARCHAR (MAX) NULL,
        [Business]     NVARCHAR (MAX) NULL,
        [NotAvailable] NVARCHAR (MAX) NULL;


GO
PRINT N'Altering [dbo].[YourJourneyLabels]...';


GO
ALTER TABLE [dbo].[YourJourneyLabels]
    ADD [BusinessFare]     NVARCHAR (MAX) NULL,
        [Cabin]            NVARCHAR (MAX) NULL,
        [BasicFare]        NVARCHAR (MAX) NULL,
        [Economy]          NVARCHAR (MAX) NULL,
        [Business]         NVARCHAR (MAX) NULL,
        [HotMealAndDrinks] NVARCHAR (MAX) NULL;


GO
PRINT N'Creating [dbo].[BusinessHandBaggages]...';


GO
CREATE TABLE [dbo].[BusinessHandBaggages] (
    [BusinessHandBaggageId] INT IDENTITY (1, 1) NOT NULL,
    [Weight]                INT NOT NULL,
    PRIMARY KEY CLUSTERED ([BusinessHandBaggageId] ASC)
);


GO
PRINT N'Creating [dbo].[SeatMappings]...';


GO
CREATE TABLE [dbo].[SeatMappings] (
    [FlightNo]   NVARCHAR (50) NOT NULL,
    [FlightType] NVARCHAR (50) NOT NULL,
    [Cabin]      NVARCHAR (50) NOT NULL
);


GO
PRINT N'Update complete.';


GO
