CREATE TABLE [dbo].[TAAccountLabels] (
    [Language]                          NVARCHAR (128) NOT NULL,
    [InternalError]                     NVARCHAR (MAX) NULL,
    [UserNotFound]                      NVARCHAR (MAX) NULL,
    [UserLocked]                        NVARCHAR (MAX) NULL,
    [PasswordExpired]                   NVARCHAR (MAX) NULL,
    [PasswordMatchesPrevious]           NVARCHAR (MAX) NULL,
    [DBUserNotFound]                    NVARCHAR (MAX) NULL,
    [TooManyFailedLoginsWithinDuration] NVARCHAR (MAX) NULL,
    [UserUnlocked]                      NVARCHAR (MAX) NULL,
    [PasswordDoesNotMatch]              NVARCHAR (MAX) NULL,
    [UserCreated]                       NVARCHAR (MAX) NULL,
    [UserNotCreated]                    NVARCHAR (MAX) NULL,
    [NotAnAdministrator]                NVARCHAR (MAX) NULL,
    [UserAlreadyExists]                 NVARCHAR (MAX) NULL,
    [UserDisabledDueToInactivity]       NVARCHAR (MAX) NULL,
    [PageTitle]                         NVARCHAR (MAX) NULL,
    [Username]                          NVARCHAR (MAX) NULL,
    [Password]                          NVARCHAR (MAX) NULL,
    [BlankUsernameTextBox]              NVARCHAR (MAX) NULL,
    [BlankPasswordTextbox]              NVARCHAR (MAX) NULL,
    [PasswordChanged]                   NVARCHAR (MAX) NULL,
    [LoginModuleTitle]                  NVARCHAR (MAX) NULL,
    [ForgottenPasswordConfirmationText] NVARCHAR (MAX) NULL,
    [AccountDoesNotExist]               NVARCHAR (MAX) NULL,
    [LoginUserName]                     NVARCHAR (MAX) NULL,
    [LoginPassword]                     NVARCHAR (MAX) NULL,
    [LoginButton]                       NVARCHAR (MAX) NULL,
    [IncompleteData]                    NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Language] ASC)
);

